import {CrudButton,GrantedPageLinks} from '../ui/PermissionControls';
import {useState,type CSSProperties,type ReactNode} from 'react';
import {useApp} from '../ui/App';

const A='/assets/financier-';
const asset={logo:A+'78786.png',avatar:A+'b66a7.png',bell:A+'bebe8.png',chevron:A+'cad8e.png',dashboard:A+'b182f.svg',budget:A+'c206d.svg',plan:A+'6f26d.svg',forecast:A+'064e4.png',requests:A+'cf824.svg',calendar:A+'852d6.svg',reports:A+'f5cb4.svg',chat:A+'f366e.svg',prev:A+'4fea3.svg',next:A+'37f23.svg',search:A+'c1f15.svg',reportDate:A+'40318.svg',plus:A+'65946.svg',camera:A+'7836e.svg',trash:A+'80a33.svg',close:A+'dd2c4.svg',edit:A+'68963.svg',print:A+'2def0.svg',modal1:A+'9b10f.png',modal2:A+'adbeb.png',modal3:A+'6d7e1.png',photo1:A+'922e5.png',photo2:A+'16023.png',photo3:A+'a2586.png',photo4:A+'83a82.png',portrait:'/assets/super-8f320.png',upload:'/assets/super-403bd.png',remove:'/assets/super-3c902.png',logout:'/assets/super-a2f9e.png',reset:'/assets/super-9e5ea.png'};
const nav=[{n:87,l:'Bosh sahifa',i:asset.dashboard},{n:88,l:'Budjetlar',i:asset.budget},{n:89,l:'Reja–fakt',i:asset.plan},{n:90,l:'Prognoz',i:asset.forecast},{n:91,l:"To‘lov so‘rovlari",i:asset.requests},{n:92,l:"To‘lov kalendari",i:asset.calendar},{n:93,l:'Hisobotlar',i:asset.reports}];
function Sidebar(){const a=useApp();return <aside className="fin-sidebar"><a className="fin-logo" href="#/screen/87"><img src={asset.logo} alt="Barpo AI"/></a><nav aria-label="Finansist menyusi">{nav.filter(x=>a.canAccess(x.n)).map(x=><a key={x.n} className={a.screen===x.n||([94,95].includes(a.screen)&&x.n===93)?'active':''} href={`#/screen/${x.n}`}><span><img src={x.i} alt=""/></span>{x.l}{(a.screen===x.n||([94,95].includes(a.screen)&&x.n===93))&&<i/>}</a>)}<GrantedPageLinks existing={nav.map(n=>n.n)}/></nav><button className={`fin-profile ${a.screen===96?'active':''}`} onClick={()=>a.go(96)}><img src={asset.avatar} alt=""/><span><b>Otabek R.</b><small>Finansist</small></span></button></aside>}
function Header({title,subtitle,actions}:{title:string;subtitle:string;actions?:ReactNode}){const a=useApp();return <header className="fin-header"><div><h1>{title}</h1><p>{subtitle}</p></div>{actions??<div className="fin-tools"><button onClick={a.toggleNotifications}><img src={asset.bell} alt="Bildirishnomalar"/><b>4</b></button><label><select aria-label="Til" value={a.language} onChange={e=>a.setLanguage(e.target.value)}><option>UZ</option><option>RU</option></select><img src={asset.chevron} alt=""/></label></div>}</header>}
function Shell({children,height=1024}:{children:ReactNode;height?:number}){return <div className="fin-shell" style={{'--fin-height':`${height}px`} as CSSProperties}><div className="fin-sidebar-slot"><Sidebar/></div>{children}</div>}
function Card({children,className=''}:{children:ReactNode;className?:string}){return <section className={`fin-card ${className}`}>{children}</section>}
function Status({children}:{children:string}){const c=['To‘landi','Tasdiqlangan','Yakunlangan'].includes(children)?'ok':['Rad etildi','Rad etilgan'].includes(children)?'bad':['Yangi'].includes(children)?'blue':'wait';return <em className={`fin-status ${c}`}>{children}</em>}
function Table({cols,rows,grid}:{cols:string[];rows:(string|ReactNode)[][];grid:string}){return <div className="fin-table"><div className="fin-table-head" style={{gridTemplateColumns:grid}}>{cols.map(x=><span key={x}>{x}</span>)}</div>{rows.map((r,i)=><div className="fin-table-row" style={{gridTemplateColumns:grid}} key={i}>{r.map((x,j)=><span key={j}>{x}</span>)}</div>)}</div>}
const kpis=(items:string[][],className='')=><div className={`fin-kpis ${className}`}>{items.map((x,i)=><article key={x[0]}><span>{x[0]}</span><strong className={x[2]??''}>{x[1]}</strong>{x[3]&&<small>{x[3]}</small>}</article>)}</div>;
function Bars({plan=false}:{plan?:boolean}){const light=plan?[92,98,108,116,110,112]:[66,77,99,116,107,136],dark=plan?[86,94,104,108,98,100]:[50,61,83,88,80,102];return <div className="fin-bars">{['Aprel','May','Iyun','Iyul','Avgust','Sentabr'].map((m,i)=><span key={m}><b><i style={{height:light[i]}}/><i style={{height:dark[i]}}/></b><small>{m}</small></span>)}</div>}
const payments=[['#PAY-3920',"Beton qorishmasi xaridi — 'Standard Build' LLC",'Materiallar','42,500,000 UZS','Kutilmoqda'],['#PAY-3919',"Oylik maosh to‘lovi (Sentyabr)",'Ish haqi','128,000,000 UZS','To‘landi'],['#PAY-3918',"G‘isht yetkazib berish xizmati",'Materiallar','18,400,000 UZS','To‘landi'],['#PAY-3917',"Kran ijarasi to‘lovi — 'TechHoist' PE",'Xizmatlar','12,300,000 UZS','Rad etildi'],['#PAY-3916',"Ofis binosi elektr energiyasi to‘lovi",'Soliqlar & Kommunal','5,100,000 UZS','Kutilmoqda']];
export function FinancierDashboardPage(){return <Shell height={948}><main className="fin-main fin-dashboard"><Header title="Moliyaviy bosh sahifa" subtitle="Moliyaviy statistik tahlillar va natijalar"/>{kpis([['Joriy balans','412,800,000 UZS'],['Oylik kirim','248,500,000 UZS'],['Oylik chiqim','186,200,000 UZS'],['Sof pul oqimi','+62,300,000 UZS'],['Budjet bajarilishi','78.4%']],'five')}<div className="fin-dashboard-charts"><Card className="fin-chart"><header><h2>Kirim-chiqim dinamikasi</h2><div><span/>Kirim <span/>Chiqim</div></header><Bars/></Card><Card className="fin-expense"><h2>Xarajatlar tarkibi</h2><div className="fin-donut"><span><b>186M</b><small>UZS</small></span></div><ul>{[['Ish haqi','38%'],['Materiallar','28%'],['Xizmatlar','15%'],['Soliqlar','12%'],['Boshqa','7%']].map(x=><li key={x[0]}><b>{x[0]}</b><span>{x[1]}</span></li>)}</ul></Card></div><Card className="fin-payment-card"><h2>Bugungi to‘lovlar</h2><Table cols={['ID','KONTRAKTLAR VA MAQSAD','KATEGORIYA','SUMMA','STATUS']} rows={payments.map(x=>[...x.slice(0,4),<Status>{x[4]}</Status>])} grid="120px 1fr 180px 150px 120px"/></Card><button className="fin-chat"><img src={asset.chat} alt="Yordamchi"/></button></main></Shell>}

const budgetRows=[['Ish haqi va ijtimoiy to‘lovlar','950,000,000 UZS','520,000,000 UZS','430,000,000 UZS','54.7%'],["Asosiy qurilish materiallari (Beton, g‘isht)",'850,000,000 UZS','612,000,000 UZS','238,000,000 UZS','72%'],['Logistika va transport xizmatlari','320,000,000 UZS','185,000,000 UZS','135,000,000 UZS','57.8%'],['Maxsus texnika ijarasi','240,000,000 UZS','142,000,000 UZS','98,000,000 UZS','59.1%'],['Kommunal xizmatlar va energiya','60,000,000 UZS','32,400,000 UZS','27,600,000 UZS','54%'],['Soliqlar va majburiy to‘lovlar','180,000,000 UZS','115,000,000 UZS','65,000,000 UZS','63.8%'],['Ofis va ma’muriy xarajatlar','50,000,000 UZS','41,600,000 UZS','8,400,000 UZS','83.2%'],['Kutilmagan va zaxira xarajatlar','200,000,000 UZS','32,000,000 UZS','168,000,000 UZS','16%']];
export function FinancierBudgetsPage(){const a=useApp();const [period,setPeriod]=useState('Yillik');return <Shell><main className="fin-main"><Header title="Budjetlar boshqaruvi" subtitle="Moliyaviy statistik tahlillar va natijalar"/><div className="fin-topline"><div className="fin-segment">{['Yillik','Oylik'].map(x=><button key={x} className={period===x?'active':''} onClick={()=>setPeriod(x)}>{x}</button>)}</div><CrudButton action="create" onClick={()=>a.notice('Yangi budjet formasi demo rejimida ochildi.')}>+ Budjet qo‘shish</CrudButton></div>{kpis([['Yillik budjet','2,850,000,000 UZS'],['Sarflangan','1,680,000,000 UZS'],['Qolgan','1,170,000,000 UZS'],['Bajarilish ko‘rsatkichi','58.9%']],'four')}<Card className="fin-large-table"><Table cols={['KATEGORIYA','YILLIK BUDJET','SARFLANGAN','QOLGAN','BAJARILISH (%)']} rows={budgetRows.map(x=>[...x.slice(0,4),<span className="fin-progress"><i style={{width:x[4]}}/>{x[4]}</span>])} grid="2fr 1.1fr 1.1fr 1.1fr 1.2fr"/></Card></main></Shell>}

const factRows=[['Ish haqi va mukofotlar','80,000,000 UZS','78,500,000 UZS','-1,500,000 UZS','98.1%'],['Materiallar sotib olish','65,000,000 UZS','54,200,000 UZS','-10,800,000 UZS','83.3%'],['Yetkazib berish xizmatlari','18,000,000 UZS','19,500,000 UZS','+1,500,000 UZS','108.3%'],["Kommunal va ijara to‘lovlari",'12,000,000 UZS','10,200,000 UZS','-1,800,000 UZS','85.0%'],['Kutilmagan xarajatlar','11,000,000 UZS','0 UZS','-11,000,000 UZS','0%']];
export function FinancierPlanFactPage(){return <Shell><main className="fin-main"><Header title="Reja va fatk tahlili" subtitle="Moliyaviy statistik tahlillar va natijalar"/>{kpis([['Rejadagi xarajatlar','186,000,000 UZS'],['Faktik xarajatlar','162,400,000 UZS'],['Farq (Tejamkorlik)','-23,600,000 UZS','green'],['Reja bajarilishi','87.3%']],'four')}<Card className="fin-plan-chart"><header><h2>6 oylik solishtirma tahlil (Reja va Fakt)</h2><div><span/>Reja <span/>Fakt</div></header><Bars plan/></Card><Card className="fin-large-table fin-fact-table"><Table cols={['KATEGORIYA','REJA','FAKT','FARQ','FOIZ']} rows={factRows.map((x,i)=>[...x.slice(0,3),<b className={i===2?'green':'red'}>{x[3]}</b>,x[4]])} grid="2fr 1fr 1fr 1fr .8fr"/></Card></main></Shell>}

export function FinancierForecastPage(){return <Shell><main className="fin-main"><Header title="Pragnoz" subtitle="Moliyaviy statistik tahlillar va natijalar"/>{kpis([['Prognoz daromad (6 oylik)','1,420,000,000 UZS'],['Prognoz xarajat (6 oylik)','1,080,000,000 UZS'],['Kutilayotgan foyda','340,000,000 UZS'],["O‘sish sur’ati (YoY)",'+12.4%']],'four')}<div className="fin-forecast-grid"><Card className="fin-line-chart"><h2>Kirim, chiqim va haqiqiy natijalar tendensiyasi</h2><div className="fin-line-legend"><i/>Prognoz kirim <i/>Prognoz chiqim <i/>Haqiqiy kirim</div><svg viewBox="0 0 650 210" aria-label="Moliyaviy prognoz chizmasi"><path className="grid" d="M20 40H630M20 90H630M20 140H630M20 190H630"/><polyline className="income" points="30,170 150,105 270,75 390,105 500,30 610,45"/><polyline className="expense" points="30,205 150,185 270,195 390,165 500,185 610,175"/><polyline className="actual" points="30,170 150,120 270,100 390,130"/>{[[30,170],[150,120],[270,100]].map((p,i)=><circle key={i} cx={p[0]} cy={p[1]} r="4"/>)}</svg><div className="fin-months">{['Oktabr','Noyabr','Dekabr','Yanvar','Fevral','Mart'].map(x=><span key={x}>{x}</span>)}</div></Card><Card className="fin-stability"><h2>Moliyaviy barqarorlik ko‘rsatkichlari</h2>{[['Likvidlik koeffitsienti','2.3x','Me’yor'],['Qarzdorlik nisbati','0.4','Sog‘lom'],['Pul oqimi yetarlilik darajasi','85%','Sariq']].map((x,i)=><article key={x[0]}><span>{x[0]}<em className={i===2?'warn':''}>{x[2]}</em></span><strong className={i===2?'orange':'green'}>{x[1]}</strong><small>{i===0?'Target: ≥ 2.0x (Kompaniya qisqa muddatli majburiyatlarini to‘liq qoplay oladi)':i===1?'Target: < 0.5 (Xususiy kapital tashqi qarzlardan yuqori)':'Target: ≥ 90% (Xarajatlar o‘sishi hisobiga zaxirani oshirish lozim)'}</small></article>)}</Card></div></main></Shell>}

const reqRows=[['#REQ-4001','Aliyor T.','Standard Build LLC',"Beton uchun to‘lov",'24,000,000 UZS','Kutilmoqda'],['#REQ-4002','Kamola A.','Solis Reklama MCHJ','SMM xizmatlari shartnomasi','8,500,000 UZS','Yangi'],['#REQ-4003','Sardor B.','Smart Office PE','Kantselyariya buyumlari','3,200,000 UZS','Tasdiqlangan'],['#REQ-4004','Aliyor T.','Trans-Logistic LLC',"Kran ijarasi to‘lovi",'15,000,000 UZS','Ko‘rib chiqilmoqda'],['#REQ-4005','Zilola H.',"G‘isht Industry","G‘isht yetkazib berish",'42,000,000 UZS','Rad etilgan'],['#REQ-4006','Sherzod K.','Apex Tech LLC','Server litsenziya xarajatlari','18,400,000 UZS','Tasdiqlangan'],['#REQ-4007','Sardor B.','UzElektro',"Elektr energiya to‘lovi",'5,100,000 UZS','Kutilmoqda']];
export function FinancierRequestsPage(){const a=useApp();return <Shell><main className="fin-main"><Header title="To’lov so’rovlari" subtitle="Moliyaviy statistik tahlillar va natijalar"/><Card className="fin-filters"><b>Filtrlar:</b><select><option>Holat: Barchasi</option></select><select><option>Kategoriya: Barchasi</option></select><select><option>Summa diapazoni</option></select><CrudButton action="create" onClick={()=>a.notice('Yangi to‘lov so‘rovi formasi ochildi.')}>+ Yangi so‘rov</CrudButton></Card><Card className="fin-large-table fin-request-table"><Table cols={['SO‘ROV','SO‘ROVCHI','KONTRAGENT','TAVSIF','SUMMA','HOLAT','HARAKATLAR']} rows={reqRows.map((x,i)=>[...x.slice(0,5),<Status>{x[5]}</Status>,[0,1,3,6].includes(i)?<span className="fin-actions"><CrudButton action="update" onClick={()=>a.notice(`${x[0]} tasdiqlandi.`)}>Tasdiqlash</CrudButton><CrudButton action="update" onClick={()=>a.notice(`${x[0]} rad etildi.`)}>Rad etish</CrudButton></span>:i===2?'11.09.2026':i===4?'10.09.2026':'09.09.2026'])} grid="110px 110px 160px 1.25fr 145px 140px 175px"/></Card></main></Shell>}

const days=[31,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,1,2,3,4];
export function FinancierCalendarPage(){return <Shell><main className="fin-main"><Header title="To’lov kalendari" subtitle="Moliyaviy statistik tahlillar va natijalar"/>{kpis([["Bugungi to‘lovlar",'3 ta (42,500,000 UZS)'],['Haftalik reja','12 ta (186,000,000 UZS)'],['Oylik umumiy','38 ta (620,000,000 UZS)']],'three small')}<div className="fin-calendar-grid"><Card className="fin-calendar"><header><h2>Sentyabr 2026</h2><div><button><img src={asset.prev} alt="Oldingi"/></button><button><img src={asset.next} alt="Keyingi"/></button></div></header><div className="fin-week">{['Dush','Sesh','Chor','Pay','Jum','Shan','Yak'].map(x=><b key={x}>{x}</b>)}</div><div className="fin-days">{days.map((d,i)=><button className={i===14?'selected':''} key={i}>{d}{[1,2,4,7,9,11,14,16,21,23,29].includes(i)&&<i className={i%3===0?'red':i%2===0?'orange':'green'}/>}</button>)}</div><footer><span><i/>Bajarilgan</span><span><i/>Rejalashtirilgan</span><span><i/>Muddati o‘tgan</span></footer></Card><Card className="fin-day-payments"><h2>14 Sentyabr, Dushanba</h2><p>Ushbu kunga rejalashtirilgan to‘lovlar ro‘yxati</p>{[["#PAY-3920","Beton qorishmasi xaridi — 'Standard Build' LLC",'42,500,000 UZS','Kutilmoqda'],['#PAY-3921',"Kommunal xizmat to‘lovi — 'UzElektro'",'5,100,000 UZS','To‘landi']].map(x=><article key={x[0]}><header><b>{x[0]}</b><Status>{x[3]}</Status></header><p>{x[1]}</p><strong>{x[2]}</strong></article>)}</Card></div></main></Shell>}

const reportRows=[['#127','24.06.2024','Kunlik','Toshkent City Blok 3','Azizov J.','Yakunlangan'],['#126','23.06.2024','Kunlik','Samarqand Turizm Markazi','Karimov M.','Jarayonda'],['#125','22.06.2024','Haftalik','Chilonzor 9-Kvartal','Tursunov Sh.','Yakunlangan'],['#124','21.06.2024','Kunlik','Toshkent City Blok 3','Azizov J.','Rad etilgan'],['#123','20.06.2024','Kunlik','Yunusobod 12-Daha','Rahimov O.','Yakunlangan'],['#122','19.06.2024','Haftalik','Buxoro Premium Rezidens','Saidov T.','Jarayonda']];
function ReportsBody({open}:{open?:boolean}){const a=useApp();const [tab,setTab]=useState('Barchasi');return <main className="fin-main fin-reports"><Header title="Hisobotlar va Tahlillar" subtitle="Platformadagi qurilish xarajatlari va resurslar hisoboti"/><div className="fin-report-toolbar"><div className="fin-segment">{['Barchasi','Kunlik','Haftalik'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div><label><img src={asset.search} alt=""/><input placeholder="Qidiruv..."/></label><button className="outline"><img src={asset.reportDate} alt=""/>Sana oralig‘ini tanlang</button><CrudButton action="create" screen={94} onClick={()=>a.go(94)}>+ Yangi hisobot</CrudButton></div><Card className="fin-reports-table"><h2>Yuborilgan hisobotlar ro‘yxati</h2><Table cols={['№','Sana','Hisobot turi','Obyekt nomi','Masʼul xodim','Holati']} rows={reportRows.map(x=>[x[0],x[1],<em className="fin-type">{x[2]}</em>,x[3],x[4],<Status>{x[5]}</Status>])} grid="70px 110px 130px 2fr 150px 130px"/></Card>{open&&<ReportModal/>}</main>}
export function FinancierReportsPage(){return <Shell height={888}><ReportsBody/></Shell>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="fin-field"><span>{label}</span>{children}</label>}
function ReportModal(){const a=useApp();return <div className="fin-shade"><form className="fin-modal" onSubmit={e=>{e.preventDefault();if(!a.canCrud(94,'create'))return;a.notice('Kunlik hisobot yuborildi.');a.go(93)}}><button type="button" className="fin-close" onClick={()=>a.go(93)}><img src={asset.close} alt="Yopish"/></button><h2>Kunlik hisobot yartish</h2><Card><h3>1. Asosiy ma’lumotlar</h3><div className="fin-form-three"><Field label="Sana"><input defaultValue="24.06.2024"/></Field><Field label="Obyekt"><select defaultValue="Toshkent City Blok 3"><option>Toshkent City Blok 3</option></select></Field><Field label="Brigadir"><input defaultValue="Otabek R."/></Field></div></Card><Card className="fin-works"><h3>2. Bajarilgan ishlar</h3>{[['Devor poydevori uchun beton quyish','m³','45'],["Armatura bog‘lash ishlari",'tonna','2.4']].map((x,i)=><div className="fin-work" key={i}><Field label="Ish nomi"><input defaultValue={x[0]}/></Field><Field label="Birlik"><select defaultValue={x[1]}><option>{x[1]}</option></select></Field><Field label="Hajmi"><input defaultValue={x[2]}/></Field><button type="button"><img src={asset.trash} alt="O‘chirish"/></button></div>)}<button type="button" className="fin-add-work">+ Ish qo‘shish</button></Card><div className="fin-modal-bottom"><Card><h3>3. Foto-hisobot</h3><div className="fin-upload"><img src={asset.camera} alt=""/><b>Rasmlarni yuklang</b><small>JPEG yoki PNG formatda</small></div><div className="fin-thumbs">{[asset.modal1,asset.modal2,asset.modal3].map(x=><img src={x} key={x} alt="Qurilish rasmi"/>)}</div></Card><Card><h3>4. Ombordan olingan materiallar</h3><Table cols={['Material nomi','Birligi','Miqdori']} rows={[["Sement (M500)",'kg','500'],['Qum (Daryo qumi)','m³','12']]} grid="1.6fr .7fr .7fr"/></Card></div><footer><button type="button" onClick={()=>a.go(93)}>Bekor qilish</button><CrudButton action="create" screen={94}>Hisobotni yuborish</CrudButton></footer></form></div>}
export function FinancierCreateReportPage(){return <Shell height={1522}><ReportsBody open/></Shell>}

export function FinancierReportDetailsPage(){const a=useApp();return <Shell height={969}><main className="fin-main fin-detail"><Header title="Kunlik hisobot #127" subtitle="Toshkent City Blok 3 loyihasining kunlik hisobot tafsilotlari" actions={<div className="fin-detail-actions"><CrudButton action="update" onClick={()=>a.go(94)}><img src={asset.edit} alt=""/>Tahrirlash</CrudButton><button onClick={()=>a.notice('Hisobot chop etishga tayyorlandi.')}><img src={asset.print} alt=""/>Chop etish</button></div>}/><div className="fin-detail-badge">Yakunlangan</div><Card className="fin-meta">{[['SANA','24.06.2024'],['OBYEKT','Toshkent City Blok 3'],['BRIGADIR (MAS’UL)','Otabek R.']].map(x=><span key={x[0]}><small>{x[0]}</small><b>{x[1]}</b></span>)}</Card><Card className="fin-detail-works"><h2>Bajarilgan ishlar ro‘yxati</h2><Table cols={['№','Ish nomi','Birligi','Hajmi']} rows={[[1,'Devor poydevori uchun beton quyish','m³',45],[2,"Armatura bog‘lash ishlari",'tonna','2.4']]} grid="50px 1fr 120px 120px"/></Card><div className="fin-detail-bottom"><Card><h2>Foto-hisobot</h2><div>{[asset.photo1,asset.photo2,asset.photo3,asset.photo4].map(x=><img src={x} key={x} alt="Qurilish rasmi"/>)}</div></Card><Card><h2>Ishlatilgan materiallar</h2><Table cols={['Material nomi','Birligi','Miqdori']} rows={[["Sement (M500)",'kg','500'],['Qum (Daryo qumi)','m³','12']]} grid="1.6fr .7fr .7fr"/></Card></div><Card className="fin-note"><b>Bosh muhandis (tasdiqlovchi) izohi:</b><p>“Beton quyish ishlari texnologik talablarga mos ravishda bajarildi. Laboratoriya sinovlari uchun namunalar olindi. Ish keyingi bosqichga o‘tishga tayyor.”</p></Card></main></Shell>}

export function FinancierProfilePage(){const a=useApp();return <Shell><main className="fin-main fin-profile-page"><Header title="Profil" subtitle="Shaxsiy ma’lumotlaringizni ko‘rish va tahrirlash"/><form className="fin-profile-form" onSubmit={e=>{e.preventDefault();a.notice('Profil ma’lumotlari saqlandi.')}}><div className="fin-profile-top"><div className="fin-profile-photo"><img src={asset.portrait} alt="Profil rasmi"/><div><button type="button"><img src={asset.upload} alt=""/>Rasm yuklash</button><button type="button"><img src={asset.remove} alt=""/>Rasm o‘chirish</button></div></div><div className="fin-profile-fields"><Field label="Ismi"><input defaultValue="Abror"/></Field><Field label="Familiya"><input defaultValue="Abrorov"/></Field><Field label="Tel raqam"><input defaultValue="+99894 364 77 03"/></Field><Field label="Parol"><input defaultValue="1q2w3e4r"/></Field></div></div><div className="fin-profile-bottom"><Field label="Lavozim"><select defaultValue="Finansist"><option>Finansist</option></select></Field><Field label="Obyektga biriktirish"><select defaultValue="-"><option>-</option></select></Field><Field label="Biriktirilgan obyectlar"><div className="fin-profile-tags">{['Navoiy ko’cha 28','Darxon avenyu','Yakkasaroy 13/10','Mirobod barpu turarjoy','Yunsobot building'].map(x=><span key={x}>{x}<b>×</b></span>)}</div></Field><Field label="Holati"><select defaultValue="faol"><option>faol</option></select></Field><Field label="Lavozimga tainlangan sana"><input placeholder="KK/OO/YYYY"/></Field></div><footer><button type="button" className="outline" onClick={()=>a.setRole('manager')}>Profildan chiqish<img src={asset.logout} alt=""/></button><div><button type="reset" className="outline"><img src={asset.reset} alt=""/>Tozalash</button><button>Tahrirlashni tasdiqlash</button></div></footer></form></main></Shell>}
