import {GrantedPageLinks} from './PermissionControls';
import {roles,loadRole,canAccess,canWrite,canCrud,roleSection,type Role} from './roles';
import {liveBackend,type CrudAction} from '../api/client';
import {RoleHome,AccessDenied} from './RoleViews';
import { Notifications } from './Notifications';
import { createContext, useContext, useEffect, useState, useCallback, Suspense, type ReactNode } from 'react';
import { screens, manifest as baseManifest } from '../screens';
import {superManifest} from '../screens/superManifest';
import {technicianManifest} from '../screens/technicianManifest';
import {platformOwnerManifest} from '../screens/platformOwnerManifest';
import {accountantManifest} from '../screens/accountantManifest';
import {financierManifest} from '../screens/financierManifest';
const manifest=[...baseManifest,...superManifest,...technicianManifest,...platformOwnerManifest,...accountantManifest,...financierManifest];
export type RecordItem={id:string;section:number;title:string;fields:Record<string,string>};
type State={canCrud:(screen:number,action:CrudAction)=>boolean;role:Role;setRole:(role:Role)=>void;canAccess:(screen:number)=>boolean;canWrite:(section:number)=>boolean;language:string;setLanguage:(value:string)=>void;notifications:boolean;toggleNotifications:()=>void;screen:number;go:(n:number)=>void;back:()=>void;values:Record<string,string>;setValue:(k:string,v:string)=>void;query:string;setQuery:(v:string)=>void;notice:(s:string)=>void;save:()=>void;records:RecordItem[];selected:RecordItem|null;select:(r:RecordItem)=>void;remove:()=>void;reportTab:string;setReportTab:(s:string)=>void};
export const AppContext=createContext<State>(null!);
export const useApp=()=>useContext(AppContext);
export const sectionFor=roleSection;
export const details:Record<number,number>={3:6,7:15,8:9,12:34,26:24,29:32};
export const creates:Record<number,number>={3:5,7:19,8:10,12:35,26:23,29:31};
export const edits:Record<number,number>={3:4,7:18,8:11,12:36,26:23,29:31};
function route(){const s=location.hash.slice(1);const n=s?Number(s.replace('/screen/','')):13;return n===14?13:n;}
export function App(){
 const [role,setRoleState]=useState<Role>(loadRole);
 const [,permissionTick]=useState(0);
 useEffect(()=>{const changed=()=>permissionTick(v=>v+1);window.addEventListener('barpo-permissions-changed',changed);return()=>window.removeEventListener('barpo-permissions-changed',changed);},[]);
 const [language,setLanguageState]=useState(()=>{try{return localStorage.getItem('barpo-language')==='RU'?'RU':'UZ';}catch{return 'UZ';}});
 const setLanguage=(value:string)=>{setLanguageState(value);try{localStorage.setItem('barpo-language',value);}catch{}};
 const [notifications,setNotifications]=useState(location.hash==='#/screen/14');const closeNotifications=useCallback(()=>setNotifications(false),[]);
 const [screen,setScreen]=useState(route),[values,setValues]=useState<Record<string,string>>({}),[query,setQuery]=useState(''),[message,setMessage]=useState(''),[records,setRecords]=useState<RecordItem[]>([]),[selected,setSelected]=useState<RecordItem|null>(null),[reportTab,setReportTab]=useState('Kunlik'),[gallery,setGallery]=useState(false);
 useEffect(()=>{const resize=()=>document.documentElement.style.setProperty('--chart-scale',String(Math.min(1,(window.innerWidth-32)/724)));resize();addEventListener('resize',resize);return()=>removeEventListener('resize',resize)},[]);
 useEffect(()=>{const fn=()=>{setScreen(route());setNotifications(location.hash==='#/screen/14');setQuery('');};addEventListener('hashchange',fn);return()=>removeEventListener('hashchange',fn)},[]);
 useEffect(()=>{if(!message)return;const t=setTimeout(()=>setMessage(''),4500);return()=>clearTimeout(t)},[message]);
 const go=(n:number)=>{if(!canAccess(role,n)){setMessage('Bu sahifa uchun ruxsat yo‘q.');return;}if(n===14){setNotifications(v=>!v);setGallery(false);return;}setNotifications(false);location.hash='/screen/'+n;setValues({});setQuery('');setGallery(false);window.scrollTo(0,0)};
 const setRole=(next:Role)=>{if(liveBackend){setMessage('Rol serverdagi hisobingizdan olinadi.');return;}const home=next==='super_admin'?41:next==='technician'?54:next==='platform_owner'?61:next==='accountant'?76:next==='financier'?87:13;setRoleState(next);try{localStorage.setItem('barpo-demo-role',next);}catch{}setValues({});setQuery('');setSelected(null);setGallery(false);setNotifications(false);location.hash='/screen/'+home;setScreen(home);document.body.classList.remove('nav-open');};
 const section=sectionFor(screen);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='Escape'&&section!==screen)go(section);};addEventListener('keydown',key);return()=>removeEventListener('keydown',key);},[screen]);
 const save=()=>{if(![27,28].includes(screen)&&(!canAccess(role,screen)||!canCrud(role,section,selected?'update':'create'))){setMessage('Bu amal uchun ruxsat yo‘q.');return;}if(screen===27||screen===28){if(!values['Telefon raqam']?.trim()||!values['Parol']?.trim()){setMessage('Telefon raqami va parolni kiriting.');return;}if(screen===28&&values['Parol']!==values['Parolni takrorlang']){setMessage('Parollar bir xil bo‘lishi kerak.');return;}}const filled=Object.entries(values).filter(([,v])=>v.trim());if(!filled.length){setMessage('Avval ma’lumotlarni kiriting.');return;}if(screen===27||screen===28){go(13);setMessage('Demo rejimiga xush kelibsiz.');return;}if(screen===0||screen===1){setMessage('Sozlamalar ushbu sessiyada saqlandi.');return;}const item={id:selected?.id??crypto.randomUUID(),section,title:filled[0][1],fields:Object.fromEntries(filled)};setRecords(rs=>selected?rs.map(r=>r.id===selected.id?item:r):[...rs,item]);setSelected(null);go(section);setMessage('Ma’lumot demo sessiyasiga saqlandi.');};
 const select=(r:RecordItem)=>{if(!canCrud(role,r.section,'update')){setMessage('Ushbu rol faqat ko‘rishi mumkin.');return;}setSelected(r);go(edits[r.section]??r.section);setValues(r.fields)};
 const remove=()=>{if(!canCrud(role,section,'delete')){setMessage('O‘chirish uchun ruxsat yo‘q.');return;}if(selected){setRecords(rs=>rs.filter(r=>r.id!==selected.id));setSelected(null);go(section);setMessage('Yozuv o‘chirildi.')}else setMessage('Figma namunaviy yozuvlari o‘zgarmaydi. Yangi yozuv qo‘shib, uni tahrirlashingiz mumkin.');};
 const Component=screens[('screen'+screen) as keyof typeof screens]??screens.screen2;
 const state={canCrud:(n:number,action:CrudAction)=>canCrud(role,n,action),role,setRole,canAccess:(n:number)=>canAccess(role,n),canWrite:(n:number)=>canWrite(role,n),language,setLanguage,notifications,toggleNotifications:()=>setNotifications(v=>!v),screen,go,back:()=>go(section===screen?13:section),values,setValue:(k:string,v:string)=>setValues(p=>({...p,[k]:v})),query,setQuery,notice:setMessage,save,records,selected,select,remove,reportTab,setReportTab};
 return <AppContext.Provider value={state}><a href="#content" className="skip-link">Asosiy mazmunga o‘tish</a><div className="mobile-header"><button onClick={()=>document.body.classList.toggle('nav-open')} aria-label="Menyuni ochish">☰</button><b>Barpo.AI</b></div><main id="content" className={'screen-view screen-'+screen} key={screen}><Suspense fallback={<div className="loading">Yuklanmoqda…</div>}>{!canAccess(role,screen)?<AccessDenied/>:screen===13&&['foreman','accountant'].includes(role)?<RoleHome/>:<Component />}</Suspense></main>{canAccess(role,screen)&&canWrite(role,section)&&records.some(r=>r.section===section)&&<aside className="session-records"><h2>Ushbu sessiyada qo‘shilganlar</h2>{records.filter(r=>r.section===section).map(r=><button key={r.id} onClick={()=>select(r)}>{r.title} <span>Tahrirlash →</span></button>)}</aside>}<button className="screen-switch" onClick={()=>setGallery(!gallery)} aria-expanded={gallery}>Ekranlar · {manifest.filter(f=>canAccess(role,+f.key.replace('screen',''))).length}</button>{gallery&&<aside className="screen-gallery" aria-label="Barcha dizayn ekranlari"><div><b>Barcha ekranlar</b><button onClick={()=>setGallery(false)} aria-label="Yopish">×</button></div><p>{liveBackend?'Sahifalar server ruxsatlari bilan filtrlangan':'Frontend demo · server ulanmagan'}</p>{manifest.filter(f=>canAccess(role,+f.key.replace('screen',''))).map(f=><button key={f.key} onClick={()=>go(+f.key.replace('screen',''))} aria-current={f.key==='screen'+screen?'page':undefined}>{f.name}</button>)}</aside>}{notifications&&<Notifications close={closeNotifications}/>} {message&&<div className="toast" role="status">{message}<button onClick={()=>setMessage('')} aria-label="Xabarni yopish">×</button></div>}</AppContext.Provider>;
}
export function Sidebar(){const a=useApp();const mainNav:[number,string,string][]=[[13,'Bosh sahifa','aa603.svg'],[26,'Obyektlar','954a5.svg'],[12,'Smetalar','2b42a.svg'],[8,'Vazifalar','3b9d7.svg'],[7,'Xomashyolar','bc942.svg'],[29,'Hisobotlar','f5cb4.svg'],[3,'Hodimlar','8bcb2.svg'],[0,'Sozlamalar','3c8ad.svg']];const adminNav:[number,string,string][]=[[37,'Foydalanuvchilar','8bcb2.svg'],[38,'Ruxsatlar','3c8ad.svg'],[39,'Obunalar','ca1f1.svg'],[40,'Kamera kuzatuvi','954a5.svg']];const link=([n,label,icon]:[number,string,string])=><a key={n} href={'#/screen/'+n} aria-current={sectionFor(a.screen)===n?'page':undefined} onClick={()=>document.body.classList.remove('nav-open')}><span className="nav-icon"><img src={'/assets/screen13-'+icon} alt=""/></span>{label}</a>;const visibleAdmin=adminNav.filter(([n])=>a.canAccess(n));return <div className="sidebar-slot"><aside className="sidebar"><div><a className="brand" href="#/screen/13"><img src="/assets/screen13-78786.png" alt="Barpo AI" width="95" height="52"/></a><nav aria-label="Asosiy menyu">{mainNav.filter(([n])=>a.canAccess(n)).map(link)}{visibleAdmin.length>0&&<><span className="nav-section-label">ADMIN BOSHQARUVI</span>{visibleAdmin.map(link)}</>}<GrantedPageLinks existing={[...mainNav,...adminNav].map(([n])=>n)}/></nav>{!liveBackend&&<label className="role-picker">Rolni sinash · demo<select aria-label="Rolni tanlash" value={a.role} onChange={e=>a.setRole(e.target.value as Role)}>{Object.entries(roles).map(([key,value])=><option key={key} value={key}>{value.label}</option>)}</select></label>}</div><button className="profile" onClick={()=>a.go(1)}><img src="/assets/screen13-b66a7.png" width="36" height="36" alt=""/><span><b>Otabek R.</b><small>{roles[a.role].label}</small></span></button></aside></div>}
export function textOf(children:ReactNode):string {if(children==null||typeof children==='boolean')return '';if(typeof children==='string'||typeof children==='number')return String(children);if(Array.isArray(children))return children.map(textOf).join(' ');if(typeof children==='object'&&'props'in children)return textOf((children.props as {children?:ReactNode}).children);return '';}
