import {useMemo,useState,type CSSProperties,type FormEvent,type ReactNode} from 'react';
import {useApp} from '../ui/App';

const A='/assets/';
const asset={
  logo:A+'super-78786.png',avatar:A+'tech-avatar-dashboard.png',chatAvatar:A+'tech-avatar-chat.png',
  portrait:A+'tech-portrait.png',bell:A+'super-bebe8.png',chevron:A+'super-cad8e.png',
  home:A+'super-81dc8.svg',requests:A+'super-57585.svg',errors:A+'super-f5cb4.svg',
  integrations:A+'super-03f22.png',settings:A+'super-3c8ad.svg',upload:A+'super-403bd.png',
  remove:A+'super-3c902.png',reset:A+'super-9e5ea.png',logout:A+'super-a2f9e.png',
};

const nav=[
  {screen:54,label:'Bosh sahifa',icon:asset.home},
  {screen:55,label:'Murojaatlar',icon:asset.requests,badge:'4'},
  {screen:56,label:'Tizim monitoringi',icon:null},
  {screen:57,label:'Xatoliklar',icon:asset.errors},
  {screen:58,label:'Integratsiyalar',icon:asset.integrations},
  {screen:59,label:'Sozlamalar',icon:asset.settings},
];

function TechSidebar(){
  const a=useApp();
  return <aside className="tech-sidebar"><a href="#/screen/54" className="tech-logo"><img src={asset.logo} alt="Barpo AI"/></a><nav aria-label="Texnik xodim menyusi">{nav.filter(item=>a.canAccess(item.screen)).map(item=><a key={item.screen} href={`#/screen/${item.screen}`} className={a.screen===item.screen?'active':''}><span className={`tech-nav-icon ${item.screen===56?'monitor-icon':''}`}>{item.icon?<img src={item.icon} alt=""/>:<i/>}</span><span>{item.label}</span>{item.badge&&<b>{item.badge}</b>}{a.screen===item.screen&&<em/>}</a>)}</nav><button className="tech-profile" onClick={()=>a.go(60)}><img src={asset.avatar} alt=""/><span><b>Jasur T.</b><small>Texnik xodim</small></span></button></aside>;
}

function TechHeader({title,subtitle}:{title:string;subtitle:string}){
  const a=useApp();return <header className="tech-header"><div><h1>{title}</h1><p>{subtitle}</p></div><div className="tech-header-tools"><button className="tech-bell" onClick={a.toggleNotifications} aria-label="Bildirishnomalar"><img src={asset.bell} alt=""/><span>4</span></button><label className="tech-language"><select aria-label="Til" value={a.language} onChange={e=>a.setLanguage(e.target.value)}><option>UZ</option><option>RU</option></select><img src={asset.chevron} alt=""/></label></div></header>;
}

function TechShell({children,height=1024}:{children:ReactNode;height?:number}){return <div className="tech-shell" style={{'--tech-height':`${height}px`} as CSSProperties}><div className="tech-sidebar-slot"><TechSidebar/></div>{children}</div>}
function Card({children,className=''}:{children:ReactNode;className?:string}){return <section className={`tech-card ${className}`}>{children}</section>}
function Legend(){return <div className="tech-legend"><span><i className="wine"/>CPU</span><span><i className="orange"/>RAM</span><span><i className="blue"/>Disk</span></div>}

function LineChart({compact=false}:{compact?:boolean}){return <div className={compact?'tech-line-chart compact':'tech-line-chart'}><svg viewBox="0 0 760 190" preserveAspectRatio="none" aria-label="Tizim resurslari grafigi"><g className="grid"><line x1="0" y1="20" x2="760" y2="20"/><line x1="0" y1="70" x2="760" y2="70"/><line x1="0" y1="120" x2="760" y2="120"/><line x1="0" y1="170" x2="760" y2="170"/></g><polyline className="cpu" points={compact?'25,132 160,92 270,155 355,48 500,82 625,34':'20,132 135,90 265,157 385,62 535,90 675,34 740,16'}/><polyline className="ram" points={compact?'25,65 160,88 275,60 395,116 505,66 650,78':'20,70 140,96 270,25 390,72 535,96 675,76 740,65'}/>{!compact&&<polyline className="disk" points="20,145 140,105 270,132 390,48 535,75 675,32 740,50"/>}</svg><div className="tech-chart-labels">{(compact?['10:00','11:00','12:00','13:00','14:00','15:00']:['00:00','04:00','08:00','12:00','16:00','20:00','24:00']).map(x=><span key={x}>{x}</span>)}</div></div>}

function BarChart(){const critical=[42,27,57,20,64,14,8],warning=[61,78,36,54,39,28,21];return <div className="tech-bar-chart">{['Dush','Sesh','Chor','Pay','Jum','Shan','Yak'].map((day,i)=><div key={day}><span className="bar-pair"><i className="critical" style={{height:`${critical[i]}px`}}/><i className="warning" style={{height:`${warning[i]}px`}}/></span><b>{day}</b></div>)}</div>}

const requests=[['Gateway ulanish xatoligi (API)','Muzaffar S. · 5 daqiqa oldin'],["Ma'lumotlar bazasi kechikishi",'Diyorbek A. · 20 daqiqa oldin'],['Kesh tozalash so‘rovi','Sardor M. · 1 soat oldin'],['SSL sertifikat yangilash','Farrux B. · 2 soat oldin'],['Log tahlili tizimi integratsiyasi','Abduvali T. · 4 soat oldin']];
const backups=[['Main Production DB','Bugun, 03:00','42.8 GB','Muvaffaqiyatli','Ertaga, 03:00','Muvaffaqiyatli o‘tdi'],['User Uploads Bucket','Kecha, 05:00','148.2 GB','Muvaffaqiyatli','24.10.2024, 05:00','Muvaffaqiyatli o‘tdi'],['AI Inference Models','20.10.2024, 01:00','850.5 GB','Xatolik','Hozir qayta...','Qayta tekshirish kutilmoqda'],['Logs & Analytics DB','Bugun, 04:30','12.4 GB','Jarayonda','Sinxronizatsiya...','Kutilmoqda'],['Static Assets Server','Bugun, 00:00','8.1 GB','Muvaffaqiyatli','24.10.2024, 00:00','Muvaffaqiyatli o‘tdi']];

export function TechnicianDashboardPage(){
  const a=useApp();return <TechShell height={1352}><main className="tech-main tech-dashboard"><TechHeader title="Texnik boshqaruv paneli" subtitle="BARPO AI platformasi texnik monitoring va boshqaruv"/><div className="tech-stats four">{[['OCHIQ MUROJAATLAR','24 ta'],['TIZIM UPTIME','99.7%'],['XATOLIKLAR SONI','18 ta'],['INTEGRATSIYALAR','12 / 14']].map(s=><article key={s[0]}><span>{s[0]}</span><strong>{s[1]}</strong></article>)}</div><div className="tech-dashboard-grid"><Card className="tech-resource-card"><header><div><h2>Tizim resurslari monitoringi</h2><p>Server CPU, RAM va Disk yuklamasi (%)</p></div><Legend/></header><LineChart compact/></Card><Card className="tech-latest"><header><h2>So‘nggi murojaatlar</h2><button onClick={()=>a.go(55)}>Barchasi</button></header>{requests.map(r=><button key={r[0]} onClick={()=>a.go(55)}><b>{r[0]}</b><small>{r[1]}</small></button>)}</Card><Card className="tech-weekly"><header><div><h2>Xatoliklar tahlili (haftalik)</h2><p>Haftalik aniqlangan xatoliklar va tizim ogohlantirishlari</p></div><div className="tech-legend"><span><i className="wine"/>Kritik</span><span><i className="orange"/>Ogohlantirish</span></div></header><BarChart/></Card><Card className="tech-integration-status"><h2>Integratsiya holati</h2>{[['SMS Gateway API','Sinxronizatsiya: 3 daqiqa oldin','Faol'],['Telegram Notification Bot','Sinxronizatsiya: 1 soat oldin','Faol'],['Payment Gateway Processing','Sinxronizatsiya: muvaffaqiyatsiz','Xato'],['AI Core Processing Engine','Sinxronizatsiya: hozirgina','Faol'],['Cloud Backup Storage','Sinxronizatsiya: rejalashtirilmoqda','Kutilmoqda']].map(x=><div key={x[0]}><span><b>{x[0]}</b><small>{x[1]}</small></span><em className={x[2]==='Xato'?'bad':x[2]==='Kutilmoqda'?'wait':''}>{x[2]}</em></div>)}</Card></div><Card className="tech-backups"><header><div><h2>Zaxira nusxalar holati</h2><p>Ma’lumotlar bazasi va faylli tizimlarning davriy zaxiralanish holatlari monitoringi</p></div><button onClick={()=>a.notice('Zaxira holatlari yangilandi.')}>↻ Yangilash</button></header><div className="backup-head"><span>TIZIM NOMI</span><span>OXIRGI ZAXIRA</span><span>HAJMI</span><span>HOLATI</span><span>KEYINGI ZAXIRA</span><span>AUDIT HOLATI</span></div>{backups.map((r,n)=><div className="backup-row" key={r[0]}>{r.map((x,i)=><span key={i} className={i===3?x==='Xatolik'?'tag bad':x==='Jarayonda'?'tag wait':'tag ok':i===5?(n<2||n===4?'green':n===2?'red':'orange'):''}>{x}</span>)}</div>)}</Card></main></TechShell>;
}

const chats=[['PL','Premium Logistika','Server yuklamasi haqida...','10:45','2'],['BI','Barpo Invest','API kaliti yangilanishi kerak','09:30',''],['UM','UzAuto Motors','Sinxronizatsiya muammosi...','Kecha','2'],['BL','B Limit','API kaliti yangilanishi kerak','09:30',''],['MH','Motors Hause','Sinxronizatsiya muammosi...','Kecha',''],['BI','Barpo Invest','API kaliti yangilanishi kerak','09:30','']];
export function TechnicianRequestsPage(){
  const a=useApp();const [tab,setTab]=useState('Aktivlar');const [filter,setFilter]=useState('Barchasi');const [query,setQuery]=useState('');const [messages,setMessages]=useState<string[]>([]);const [draft,setDraft]=useState('');const visible=useMemo(()=>chats.filter(c=>c[1].toLowerCase().includes(query.toLowerCase())),[query]);const send=(e:FormEvent)=>{e.preventDefault();if(!draft.trim())return;setMessages(m=>[...m,draft]);setDraft('');};return <TechShell><main className="tech-main tech-chat-page"><TechHeader title="Murojaatlar (Chat)" subtitle="Foydalanuvchilar murojaatlari va texnik yordam chat interfeysi"/><div className="tech-chat-layout"><Card className="tech-chat-list"><label className="tech-chat-search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Qidirish..."/></label><div className="tech-segment">{['Aktivlar','Yakunlanganlar'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div><div className="tech-chat-filters">{['Barchasi','Ko‘rilgan','Ko‘rilmagan'].map(x=><button className={filter===x?'active':''} onClick={()=>setFilter(x)} key={x}>{x}{x==='Ko‘rilmagan'&&<b>4</b>}</button>)}</div><div className="tech-contact-list">{visible.map((c,i)=><button className={i===0?'selected':''} key={c[1]+i}><i>{c[0]}</i><span><b>{c[1]}</b><small>{c[2]}</small></span><time>{c[3]}</time>{c[4]&&<em>{c[4]}</em>}</button>)}</div></Card><Card className="tech-conversation"><header><div className="tech-chat-user"><i>PL</i><span><b>Premium Logistika</b><small>Murojaat #MR-2481: Server yuklamasi</small></span></div><button onClick={()=>a.notice('Murojaat yakunlangan sifatida belgilandi.')}>✓ Yakunlansin</button></header><div className="tech-messages"><span className="today">Bugun</span><div className="message incoming"><b>Premium Logistika · Client</b><p>Assalomu alaykum! Bizning serverda yuklanish 95% dan oshib ketdi. Ilovamiz sekinlashyapti va ba’zi foydalanuvchilar kira olmayapti.</p><time>09:15</time></div><div className="message incoming"><b>Premium Logistika · Client</b><p>CPU va RAM ko‘rsatkichlari juda yuqori ko‘rsatyapti. Iltimos, tezda ko‘rib chiqing.</p><time>09:16</time></div><div className="message outgoing"><b>Jasur T. · Texnik xodim</b><p>Vaalaykum assalom! Tushundim, hozir tekshirib ko‘raman. Qaysi serverda aniq muammo bor?</p><time>09:20</time></div><div className="message incoming"><b>Premium Logistika · Client</b><p>Asosiy production server — srv-prod-01. Bugundan beri bunday holat.</p><time>09:22</time></div>{messages.map((m,i)=><div className="message outgoing" key={i}><b>Jasur T. · Texnik xodim</b><p>{m}</p><time>Hozir</time></div>)}</div><form onSubmit={send} className="tech-chat-compose"><button type="button">＋</button><input value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Xabar yozing..."/><button>Yuborish</button></form></Card></div></main></TechShell>;
}

const processes=[['nginx-load-balancer','Faol','99.98%'],['mysql-master-db','Faol','99.95%'],['barpo-ai-inference','Faol','99.90%'],['redis-cache-service','Ogohlantirish','98.45%'],['rabbitmq-message-broker','Faol','99.99%'],['backup-cron-job','Xato','85.20%']];
const events=[['11:58:20','Database connection pools exhausted'],['11:55:04','Disk space exceeds 85% on static-server'],['11:42:15','AI model recalculation triggered'],['11:30:00','Daily snapshot backup completed successfully'],['11:15:22','High traffic spike detected on API gateway'],['11:02:10','SSL Certificate verification failed on sub-domain']];
export function TechnicianMonitoringPage(){return <TechShell><main className="tech-main tech-monitoring"><TechHeader title="Tizim monitoringi" subtitle="Server va tizim resurslari holati"/><div className="tech-stats three progress-stats">{[['CPU YUKLAMASI','34%','34'],['RAM ISHLATILISHI','67%','67'],['DISK HAJMI','2.4 TB / 4 TB','41']].map((s,i)=><article key={s[0]}><span>{s[0]}</span><strong>{s[1]}</strong><i><u className={i===1?'orange':i===2?'blue':''} style={{width:s[2]+'%'}}/></i></article>)}</div><Card className="tech-monitor-chart"><header><div><h2>Server resurslari (24 soat)</h2><p>Barcha yuklamalar dinamikasi</p></div><Legend/></header><LineChart/></Card><div className="tech-monitor-bottom"><Card><h2>Faol jarayonlar</h2>{processes.map(x=><div className="process-row" key={x[0]}><span><i className={x[1]==='Xato'?'red':x[1]==='Ogohlantirish'?'orange':''}/><b>{x[0]}</b></span><em>{x[1]}</em><strong>{x[2]}</strong></div>)}</Card><Card><h2>Tizim hodisalari</h2>{events.map(x=><div className="event-row" key={x[0]}><time>{x[0]}</time><span>{x[1]}</span></div>)}</Card></div></main></TechShell>}

const errorRows=[['ERR_DB_TIMEOUT','Database Connection Timeout','Database Pool','Yuqori','Bugun, 10:30:15','18 marta'],['ERR_API_RATELIMIT','Rate limit exceeded on public endpoint','API Gateway','O‘rta','Bugun, 09:12:44','156 marta'],['ERR_MEM_OVERFLOW','Memory limit allocation failed','Worker Node 3','Kritik','Kecha, 23:40:11','3 marta'],['ERR_SSL_EXPIRED','SSL handshake certificate validation fail...','Security Manager','O‘rta','Kecha, 18:15:30','1 marta'],['ERR_REDIS_CONN','Redis backup node unavailable','Cache Cluster','Past','24.10.2024','12 marta'],['ERR_SMTP_FAIL','Mail notification delivery failed','Notifier Worker','Past','24.10.2024','89 marta']];
export function TechnicianErrorsPage(){const [query,setQuery]=useState('');const rows=errorRows.filter(r=>r.join(' ').toLowerCase().includes(query.toLowerCase()));return <TechShell height={1116}><main className="tech-main tech-errors"><TechHeader title="Xatoliklar" subtitle="Tizim xatoliklari va diagnostika"/><div className="tech-stats four">{[['BUGUNGI XATOLIKLAR','7 ta'],["HAFTALIK O'RTACHA",'18 ta'],['KRITIK XATOLIKLAR','2 ta'],['HAL QILINGAN','89%']].map(s=><article key={s[0]}><span>{s[0]}</span><strong>{s[1]}</strong></article>)}</div><Card className="tech-error-chart"><header><div><h2>Xatoliklar dinamikasi (haftalik)</h2><p>Haftalik aniqlangan xatoliklar va tizim ogohlantirishlari</p></div><div className="tech-legend"><span><i className="wine"/>Kritik</span><span><i className="orange"/>Ogohlantirish</span></div></header><BarChart/></Card><div className="tech-error-filters"><label>⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Xomashyolarni qidirish..."/></label><select><option>Muhimlik</option><option>Kritik</option><option>Past</option></select><input placeholder="KK.OO.YYYY"/></div><Card className="tech-error-table"><h2>Diagnostika jurnali</h2><div className="error-head"><span>XATOLIK KODI</span><span>XABAR</span><span>MODUL</span><span>MUHIMLIK</span><span>SANA VA VAQT</span><span>TAKRORLANISH</span></div>{rows.map(r=><div className="error-row" key={r[0]}>{r.map((x,i)=><span key={i} className={i===3?`severity ${x==='Kritik'?'critical':x==='Past'?'low':'medium'}`:''}>{x}</span>)}</div>)}</Card></main></TechShell>}

const services=[['Didox','Soliq hujjatlari va elektron hisob-fakturalar','Bugun, 10:42','Ulangan','▣'],['iHamkor','Bank hisoblari va tranzaksiyalar','Bugun, 09:18','Ulangan','▥'],['Telegram bot','Xodimlar uchun tezkor bildirishnomalar','Kecha, 18:05','Ulangan','➤'],['SMS xizmati','Tasdiqlash kodlari va ogohlantirishlar','Sinxronlanmagan','Uzilgan','◯']];
export function TechnicianIntegrationsPage(){const a=useApp();return <TechShell height={960}><main className="tech-main tech-integrations"><TechHeader title="Integratsiyalar" subtitle="Tashqi tizimlar ulanishi va ma’lumot almashinuvini boshqaring"/><div className="tech-small-stats">{[['4','Xizmatlar'],['3','Faol ulanish'],['1','E’tibor talab qiladi']].map(x=><article key={x[1]}><strong>{x[0]}</strong><span>{x[1]}</span></article>)}</div><Card className="tech-services"><header><h2>Ulangan xizmatlar</h2><p>ERP bilan ishlaydigan tashqi xizmatlar holati</p></header><div className="tech-service-grid">{services.map(s=><article key={s[0]}><div className="service-title"><i>{s[4]}</i><span><b>{s[0]}</b><small>{s[1]}</small></span><em className={s[3]==='Uzilgan'?'bad':''}>● {s[3]}</em></div><div className="service-footer"><span><small>Oxirgi sinxronizatsiya</small><b>{s[2]}</b></span><button onClick={()=>a.notice(`${s[0]} sozlamalari demo rejimida ochildi.`)}>Sozlash</button></div></article>)}</div></Card></main></TechShell>}

function Field({label,children,className=''}:{label:string;children:ReactNode;className?:string}){return <label className={`tech-field ${className}`}><span>{label}</span>{children}</label>}
export function TechnicianSettingsPage(){const a=useApp();const [switches,setSwitches]=useState([true,false,true,true]);return <TechShell><main className="tech-main tech-settings"><TechHeader title="Tizim Sozlamalari" subtitle="Platforma xarakteristikalari va bildirishnomalarni boshqarish"/><Card className="tech-settings-card"><header><h2>Umumiy Sozlamalar</h2><p>Tashkilotingiz uchun standart til, valyuta va vaqt sozlamalarini boshqaring</p></header><div className="tech-settings-fields"><Field label="Platforma nomi" className="wide"><input defaultValue="BuildFlow"/></Field><Field label="Tizim tili (Language)" className="wide"><select><option>O‘zbekcha</option></select></Field><Field label="Vaqt mintaqasi" className="wide"><select><option>(UTC+5) Toshkent mintaqasi</option></select></Field><Field label="Tizim valyutasi"><input defaultValue="UZS (so‘m)"/></Field><Field label="Sana formati"><select><option>KK.OO.YYYY</option></select></Field></div><div className="tech-notification-settings"><header><h2>Bildirishnoma sozlamalari</h2><p>Tizim yangiliklari va vazifa eslatmalari yuboriladigan kanallarni tanlang</p></header>{['Email bildirishnomalari','SMS bildirishnomalari','Telegram bildirishnomalari','Vazifa eslatmalari'].map((label,i)=><button key={label} onClick={()=>setSwitches(s=>s.map((v,n)=>n===i?!v:v))}><span><b>{label}</b><small>{['Smeta tasdiqlari va moliyaviy hisobotlar email pochtaga yuboriladi','Favqulodda vazifa o‘zgarishlari va ogohlantirishlar telefon raqamga yuboriladi','BuildFlow boti orqali kunlik vazifa eslatmalarini faollashtirish','Belgilangan muddatdan 24 soat oldin tizimda eslatma ko‘rsatish'][i]}</small></span><i className={switches[i]?'on':''}><u/></i></button>)}</div><footer><button onClick={()=>a.notice('Tizim sozlamalari saqlandi.')}>Saqlash</button></footer></Card></main></TechShell>}

export function TechnicianProfilePage(){const a=useApp();return <TechShell><main className="tech-main tech-profile-page"><TechHeader title="Profil" subtitle="Shaxsiy ma’lumotlaringizni ko‘rish va tahrirlash"/><form className="tech-profile-card" onSubmit={e=>{e.preventDefault();a.notice('Profil ma’lumotlari saqlandi.')}}><div className="tech-profile-top"><div className="tech-photo-box"><img className="tech-portrait" src={asset.portrait} alt="Profil rasmi"/><div><button type="button"><img src={asset.upload} alt=""/>Rasm yuklash</button><button type="button"><img src={asset.remove} alt=""/>Rasm o‘chirish</button></div></div><div className="tech-profile-fields"><Field label="Ismi"><input defaultValue="Abror"/></Field><Field label="Familiya"><input defaultValue="Abrorov"/></Field><Field label="Tel raqam"><input defaultValue="+99894 364 77 03"/></Field><Field label="Parol"><input defaultValue="1q2w3e4r"/></Field></div></div><div className="tech-profile-bottom"><Field label="Lavozim"><select><option>Prorab</option></select></Field><Field label="Obyektga biriktirish"><select><option>-</option></select></Field><Field label="Biriktirilgan obyectlar"><div className="tech-tags">{['Navoiy ko’cha 28','Darxon avenyu','Yakkasaroy 13/10','Mirobod barpu turarjoy','Yunsobot building'].map(x=><span key={x}>{x}<b>×</b></span>)}</div></Field><Field label="Holati"><select><option>faol</option></select></Field><Field label="Lavozimga tainlangan sana"><input placeholder="KK/OO/YYYY"/></Field></div><footer><button type="button" className="outline" onClick={()=>a.setRole('manager')}>Profildan chiqish <img src={asset.logout} alt=""/></button><div><button type="reset" className="outline"><img src={asset.reset} alt=""/>Tozalash</button><button>Tahrirlashni tasdiqlash</button></div></footer></form></main></TechShell>}
