import {CrudButton,GrantedPageLinks} from '../ui/PermissionControls';
import {useState,type CSSProperties,type ReactNode} from 'react';
import {useApp} from '../ui/App';

const A='/assets/';
const asset={logo:A+'super-78786.png',avatar:A+'accountant-avatar.png',bell:A+'super-bebe8.png',chevron:A+'super-cad8e.png',dashboard:A+'accountant-dashboard.svg',documents:A+'accountant-documents.svg',invoices:A+'accountant-invoices.svg',wallet:A+'accountant-wallet.svg',contractors:A+'accountant-contractors.svg',payroll:A+'accountant-payroll.svg',reconcile:A+'accountant-reconcile.svg',reports:A+'accountant-reports.svg',requests:A+'accountant-requests.png',chatbot:A+'owner-chatbot.png',portrait:A+'super-8f320.png',upload:A+'super-403bd.png',remove:A+'super-3c902.png',logout:A+'super-a2f9e.png',reset:A+'super-9e5ea.png',constructing:A+'super-8170b.png',reportBalance:A+'accountant-report-balance.svg',reportProfit:A+'accountant-report-profit.svg',reportTax:A+'accountant-report-tax.svg',reportCash:A+'accountant-report-cash.svg',reportDebt:A+'accountant-report-debt.svg',reportStock:A+'accountant-report-stock.svg'};
const nav=[{screen:76,label:'Bosh sahifa',icon:asset.dashboard},{screen:77,label:'Birlamchi hujjatlar',icon:asset.documents},{screen:78,label:'Hisoblar',icon:asset.invoices},{screen:79,label:'Bank va kassa',icon:asset.wallet},{screen:80,label:'Kontragentlar',icon:asset.contractors},{screen:81,label:'Ish haqi',icon:asset.payroll},{screen:82,label:'Solishtirish',icon:asset.reconcile},{screen:83,label:'Hisobotlar',icon:asset.reports},{screen:84,label:'Talabnomalar',icon:asset.requests}];
function AccountantSidebar(){const a=useApp();return <aside className="acc-sidebar"><a href="#/screen/76" className="acc-logo"><img src={asset.logo} alt="Barpo AI"/></a><nav aria-label="Buxgalter menyusi">{nav.filter(n=>a.canAccess(n.screen)).map(n=><a key={n.screen} className={a.screen===n.screen?'active':''} href={`#/screen/${n.screen}`}><span><img src={n.icon} alt=""/></span>{n.label}{a.screen===n.screen&&<i/>}</a>)}<GrantedPageLinks existing={nav.map(n=>n.screen)}/></nav><button className="acc-profile" onClick={()=>a.go(85)}><img src={asset.avatar} alt=""/><span><b>Madina R.</b><small>Buxgalter</small></span></button></aside>}
function AccountantHeader({title,subtitle}:{title:string;subtitle:string}){const a=useApp();return <header className="acc-header"><div><h1>{title}</h1><p>{subtitle}</p></div><div className="acc-header-tools"><button onClick={a.toggleNotifications}><img src={asset.bell} alt="Bildirishnomalar"/><b>4</b></button><label><select aria-label="Til" value={a.language} onChange={e=>a.setLanguage(e.target.value)}><option>UZ</option><option>RU</option></select><img src={asset.chevron} alt=""/></label></div></header>}
function AccountantShell({children,height=1024}:{children:ReactNode;height?:number}){return <div className="acc-shell" style={{'--acc-height':`${height}px`} as CSSProperties}><div className="acc-sidebar-slot"><AccountantSidebar/></div>{children}</div>}
function Card({children,className=''}:{children:ReactNode;className?:string}){return <section className={`acc-card ${className}`}>{children}</section>}
function Status({value}:{value:string}){const cls=['Tasdiqlangan','To‘langan','Mos'].includes(value)?'ok':['Kutilmoqda'].includes(value)?'wait':['Rad etilgan','To‘lanmagan','Nomuvofiq','Muddati o‘tgan'].includes(value)?'bad':'';return <em className={`acc-status ${cls}`}>{value}</em>}
function Table({columns,rows,grid,className=''}:{columns:string[];rows:string[][];grid:string;className?:string}){return <div className={`acc-table ${className}`}><div className="acc-table-head" style={{gridTemplateColumns:grid}}>{columns.map(c=><span key={c}>{c}</span>)}</div>{rows.map((r,n)=><div className="acc-table-row" style={{gridTemplateColumns:grid}} key={n}>{r.map((v,i)=><span key={i} className={v.includes('000')?(i>2&&['-','0 UZS'].indexOf(v)<0?(v.startsWith('4')||v.startsWith('8')||v.startsWith('1')?'money':''):''):''}>{i===r.length-1&&['Tasdiqlangan','Kutilmoqda','Rad etilgan','To‘langan','To‘lanmagan','Mos','Nomuvofiq','Muddati o‘tgan'].includes(v)?<Status value={v}/>:v}</span>)}</div>)}</div>}
function Legend(){return <div className="acc-legend"><span><i/>Kirim</span><span><i/>Chiqim</span></div>}
function IncomeChart(){const a=[88,110,120,92,108,136],b=[54,70,79,66,87,64];return <div className="acc-income-chart"><div className="acc-axis"><span>150M</span><span>100M</span><span>50M</span><span>0</span></div>{['Yan','Fev','Mar','Apr','May','Iyun'].map((x,i)=><div key={x}><span><i style={{height:a[i]}}/><i style={{height:b[i]}}/></span><b>{x}</b></div>)}</div>}
const operations=[['24.10.2025','Mijozlardan to‘lov (Nova Tech)','Nova Tech','42,000,000 UZS','Kirim','Tasdiqlangan'],['23.10.2025','Ofis ijarasi','Atlas Group','8,500,000 UZS','Chiqim','Tasdiqlangan'],['21.10.2025','Server xizmatlari to‘lovi','AWS Direct','4,200,000 UZS','Chiqim','Kutilmoqda'],['19.10.2025','Konsalting shartnomasi','Orzu Education','12,500,000 UZS','Kirim','Tasdiqlangan'],['18.10.2025','Ish qurollari sotib olish','Baraka Retail','2,100,000 UZS','Chiqim','Rad etilgan']];

export function AccountantDashboardPage(){return <AccountantShell height={936}><main className="acc-main acc-dashboard"><AccountantHeader title="Buxgalteriya boshqaruv paneli" subtitle="Barcha moliyaviy amallar va hisoblar bo‘yicha umumiy ko‘rsatkichlar"/><div className="acc-kpis five">{[['JORIY BALANS','234,500,000 UZS'],['OYLIK KIRIM','139,500,000 UZS'],['OYLIK CHIQIM','62,600,000 UZS'],['DEBITORLIK QARZI','28,400,000 UZS'],['KREDITORLIK QARZI','18,200,000 UZS']].map((x,i)=><article key={x[0]}><span>{x[0]}</span><strong className={i===3?'orange':i===4?'red':''}>{x[1]}</strong></article>)}</div><div className="acc-dashboard-charts"><Card className="acc-chart-card"><header><div><h2>Kirim-chiqim dinamikasi</h2><p>Yanvar-Iyun oylariga qiyosiy ko‘rsatkichlar</p></div><Legend/></header><IncomeChart/></Card><Card className="acc-expenses"><h2>Xarajatlar taqsimoti</h2><div className="acc-donut"><span><b>62.6M</b><small>Jami UZS</small></span></div><ul>{[['Ish haqi','45%'],['Soliqlar','20%'],['Ijara','15%'],['Xizmatlar','12%'],['Boshqa','8%']].map(x=><li key={x[0]}><b>{x[0]}</b><span>{x[1]}</span></li>)}</ul></Card></div><Card className="acc-recent"><h2>Oxirgi operatsiyalar</h2><Table columns={['SANA','HUJJAT / TAVSIF','KONTRAGENT','SUMMA','TURI','HOLAT']} rows={operations} grid="130px 1.6fr 1fr 150px 110px 140px"/></Card><button className="acc-chatbot"><img src={asset.chatbot} alt="Yordamchi"/></button></main></AccountantShell>}

const documents=[['SF-2026-001','Schyot-faktura','Nova Tech Solutions','12.10.2025','42,000,000 UZS','Tasdiqlangan'],['DL-2026-015','Dalolatnoma','Baraka Retail MChJ','14.10.2025','8,500,000 UZS','Tasdiqlangan'],['SH-2026-042','Shartnoma','Orzu Education holding','15.10.2025','120,000,000 UZS','Kutilmoqda'],['SF-2026-002','Schyot-faktura','Atlas Group','18.10.2025','5,300,000 UZS','Rad etilgan'],['DL-2026-016','Dalolatnoma','Zamin Logistics Group','20.10.2025','24,000,000 UZS','Tasdiqlangan'],['SF-2026-003','Schyot-faktura','Apex Core','22.10.2025','18,200,000 UZS','Kutilmoqda'],['SF-2026-004','Schyot-faktura','Build Up Construction','23.10.2025','9,600,000 UZS','Tasdiqlangan']];
export function AccountantDocumentsPage(){const a=useApp();return <AccountantShell><main className="acc-main acc-list-page"><AccountantHeader title="Birlamchi hujjatlar" subtitle="Kiruvchi va chiquvchi hujjatlarni boshqarish"/><div className="acc-toolbar"><div><button>▣ Sana: 01.10 - 31.10.2025</button><select><option>Turi: Hammasi</option></select><select><option>Holati: Tasdiqlangan</option></select></div><CrudButton action="create" onClick={()=>a.notice('Yangi hujjat formasi demo rejimida ochildi.')}>+ Hujjat qo‘shish</CrudButton></div><Card className="acc-table-card"><Table columns={['HUJJAT RAQAMI','TURI','KONTRAGENT','SANA','SUMMA','HOLATI']} rows={documents} grid="160px 200px 1.5fr 140px 160px 140px"/></Card></main></AccountantShell>}

const invoices=[['INV-2025-104','Nova Tech Solutions','02.10.2025','15.10.2025','42,000,000','42,000,000','0','To‘langan'],['INV-2025-105','Baraka Retail MChJ','05.10.2025','20.10.2025','18,500,000','8,500,000','10,000,000','Kutilmoqda'],['INV-2025-106','Orzu Education holding','08.10.2025','25.10.2025','35,000,000','0','35,000,000','To‘lanmagan'],['INV-2025-107','Apex Core','10.10.2025','24.10.2025','12,200,000','12,200,000','0','To‘langan'],['INV-2025-108','Zamin Logistics Group','12.10.2025','30.10.2025','24,000,000','24,000,000','0','To‘langan'],['INV-2025-109','Build Up Construction','15.10.2025','05.11.2025','9,600,000','0','9,600,000','Kutilmoqda']];
export function AccountantInvoicesPage(){const [tab,setTab]=useState('Schyot-fakturalar');return <AccountantShell><main className="acc-main acc-invoices"><AccountantHeader title="Hisoblar va dalolatnomalar" subtitle="Schyot-fakturalar va solishtirma dalolatnomalar"/><div className="acc-tabs">{['Schyot-fakturalar','Dalolatnomalar'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div><div className="acc-kpis four compact">{[['Jami hisoblar','48 ta'],['Tasdiqlangan','35 ta'],['Kutilmoqda','8 ta'],['Muddati o‘tgan','5 ta']].map((x,i)=><article key={x[0]}><span>{x[0]}</span><strong className={i===1?'green':i===2?'orange':i===3?'red':''}>{x[1]}</strong></article>)}</div><Card className="acc-table-card"><Table columns={['HISOB RAQAMI','KONTRAGENT','SANA','TO‘LOV MUDDATI','SUMMA','TO‘LANGAN','QOLDIQ','HOLAT']} rows={invoices} grid="140px 1.4fr 130px 140px 140px 140px 120px 130px"/></Card></main></AccountantShell>}

const bankRows=[['24.10.2025','Mijozlardan to‘lov (Nova Tech)','Nova Tech Solutions','42,000,000','-','198,300,000 UZS'],['23.10.2025','Ofis ijarasi','Atlas Group','-','8,500,000','156,300,000 UZS'],['20.10.2025','Soliq to‘lovi (QQS)','Davlat Soliq Qo‘mitasi','-','12,800,000','164,800,000 UZS'],['18.10.2025','Shartnoma to‘lovi','Baraka Retail MChJ','85,000,000','-','177,600,000 UZS'],['15.10.2025','Ish haqi to‘lovlari','Xodimlar hisob raqamlari','-','35,000,000','92,600,000 UZS'],['12.10.2025','Server xizmati (AWS)','AWS Direct','-','4,200,000','127,600,000 UZS']];
export function AccountantBankPage(){const a=useApp();const [tab,setTab]=useState('Bank operatsiyalari');return <AccountantShell><main className="acc-main acc-bank"><AccountantHeader title="Bank va kassa" subtitle="Bank operatsiyalari va kassa hisobi"/><div className="acc-bank-balances"><article><span>Bank hisobi (Kapitalbank)</span><strong>198,300,000 UZS</strong><i>⌁</i></article><article><span>Kassa balansi</span><strong>36,200,000 UZS</strong></article></div><div className="acc-row-toolbar"><div className="acc-tabs">{['Bank operatsiyalari','Kassa operatsiyalari'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div><CrudButton action="create" onClick={()=>a.notice('Operatsiya qo‘shish formasi demo rejimida.')}>+ Operatsiya qo‘shish</CrudButton></div><Card className="acc-table-card"><Table columns={['SANA','HUJJAT / TAVSIF','KONTRAGENT','KIRIM','CHIQIM','QOLDIQ BALANS']} rows={bankRows} grid="130px 1.5fr 1.2fr 150px 150px 170px"/></Card></main></AccountantShell>}

const contractors=[['Nova Tech Solutions','301245789','42,000,000 UZS','0 UZS','24.10.2025','Tasdiqlangan'],['Orzu Education holding','208451963','28,400,000 UZS','12,500,000 UZS','21.10.2025','Kutilmoqda'],['Baraka Retail MChJ','305147820','0 UZS','18,200,000 UZS','18.10.2025','Muddati o‘tgan'],['Atlas Group','309652147','5,300,000 UZS','8,500,000 UZS','23.10.2025','Tasdiqlangan'],['Zamin Logistics Group','310452789','24,000,000 UZS','0 UZS','20.10.2025','Tasdiqlangan'],['Grand Trans Servis','204856931','15,200,000 UZS','3,200,000 UZS','15.10.2025','Kutilmoqda']];
export function AccountantContractorsPage(){const a=useApp();return <AccountantShell><main className="acc-main acc-contractors"><AccountantHeader title="Kontragentlar bilan hisob-kitob" subtitle="Debitorlik va kreditorlik qarzi holati"/><div className="acc-kpis three compact">{[['JAMI DEBITORLIK QARZI','28,400,000 UZS'],['JAMI KREDITORLIK QARZI','18,200,000 UZS'],['MUDDATI O‘TGAN QARZLAR','8,600,000 UZS']].map((x,i)=><article key={x[0]}><span>{x[0]}</span><strong className={i===0?'orange':'red'}>{x[1]}</strong></article>)}</div><div className="acc-row-toolbar"><select><option>Turi: Hammasi</option></select><CrudButton action="create" onClick={()=>a.notice('Yangi kontragent formasi demo rejimida.')}>+ Yangi kontragent</CrudButton></div><Card className="acc-table-card"><Table columns={['KONTRAGENT','INN','DEBITORLIK','KREDITORLIK','OXIRGI OPERATSIYA','HOLAT']} rows={contractors} grid="1.4fr 140px 170px 170px 170px 150px"/></Card></main></AccountantShell>}

const payroll=[['Alimov Sanjarbek O.','Dasturchi','12,000,000','1,500,000','1,350,000','12,150,000 UZS','To‘langan'],['Karimova Gulnoza R.','HR menejer','6,500,000','500,000','700,000','6,300,000 UZS','To‘langan'],['Sodiqov Dilmurod P.','Sotuv menejeri','5,000,000','3,200,000','820,000','7,380,000 UZS','To‘langan'],['Raximov Rustam I.','Tizim ma’muri','7,000,000','0','700,000','6,300,000 UZS','Kutilmoqda'],['Usmanova Shaxnoza T.','Ofis menejeri','4,500,000','200,000','470,000','4,230,000 UZS','To‘langan'],['Azimov Temur G.','Marketolog','8,000,000','1,200,000','920,000','8,280,000 UZS','Kutilmoqda']];
export function AccountantPayrollPage(){const a=useApp();return <AccountantShell><main className="acc-main acc-payroll"><AccountantHeader title="Ish haqi va xodimlar" subtitle="Xodimlar ish haqi hisob-kitobi"/><div className="acc-kpis four compact">{[['JAMI ISH HAQI FONDI','45,000,000 UZS'],['HISOBLANGAN ISH HAQI','35,000,000 UZS'],['TO‘LANGAN ISH HAQI','28,500,000 UZS'],['TO‘LANADIGAN QOLDIQ','6,500,000 UZS']].map((x,i)=><article key={x[0]}><span>{x[0]}</span><strong className={i===1?'blue':i===2?'green':i===3?'orange':''}>{x[1]}</strong></article>)}</div><div className="acc-row-toolbar"><button className="outline">▣ Davr: Sentyabr 2026</button><CrudButton action="create" onClick={()=>a.notice('Ish haqi hisoblash demo rejimida bajarildi.')}>+ Ish haqi hisoblash</CrudButton></div><Card className="acc-table-card"><Table columns={['XODIM','LAVOZIM','OKLAD (UZS)','BONUS','USHLANMA','JAMI (NET)','HOLAT']} rows={payroll} grid="1.5fr 1.2fr 130px 130px 130px 150px 130px"/></Card></main></AccountantShell>}

const reconcile=[['SF-2026-001 (Schyot-faktura)','12.10.2025','42,000,000 UZS','42,000,000 UZS','0 UZS','Mos'],['SF-2026-002 (Schyot-faktura)','18.10.2025','5,300,000 UZS','0 UZS','5,300,000 UZS','Nomuvofiq'],['DL-2026-015 (Dalolatnoma)','14.10.2025','8,500,000 UZS','8,500,000 UZS','0 UZS','Mos'],['SH-2026-042 (Shartnoma)','15.10.2025','120,000,000 UZS','120,000,000 UZS','0 UZS','Mos'],['SF-2026-003 (Schyot-faktura)','22.10.2025','18,200,000 UZS','18,000,000 UZS','200,000 UZS','Nomuvofiq']];
export function AccountantReconciliationPage(){const a=useApp();return <AccountantShell><main className="acc-main acc-reconcile"><AccountantHeader title="Solishtirish" subtitle="Kontragentlar bilan solishtirma dalolatnomalar"/><div className="acc-row-toolbar"><div><select><option>Kontragent: Nova Tech Solutions</option></select><button className="outline">▣ Davr: 01.10 - 31.10.2025</button></div><button onClick={()=>a.notice('Solishtirma dalolatnoma shakllantirildi.')}>Dalolatnoma shakllantirish</button></div><Card className="acc-reconcile-summary"><h2>Bizning ma’lumot vs Kontragent ma’lumoti</h2><div>{[['Biz bo‘yicha jami kirim','194,000,000 UZS','green'],['Kontragent bo‘yicha jami chiqim','188,500,000 UZS','green'],['Tafovut / Farq','5,500,000 UZS','red']].map(x=><span key={x[0]}><small>{x[0]}</small><strong className={x[2]}>{x[1]}</strong></span>)}</div></Card><Card className="acc-table-card"><Table columns={['HUJJAT','SANA','BIZNING SUMMA','KONTRAGENT SUMMASI','FARQ','HOLATI']} rows={reconcile} grid="1.6fr 140px 170px 190px 150px 130px"/></Card></main></AccountantShell>}

const reportCards=[['Balans hisoboti','Yangilangan: Bugun, 10:24','Kompaniyaning aktivlari, passivlari va xususiy kapitali holati to‘g‘risida hisobot',asset.reportBalance],['Foyda va zarar hisoboti','Yangilangan: Kecha, 18:00','Daromadlar, xarajatlar va hisobot davri bo‘yicha yakuniy moliyaviy natijalar',asset.reportProfit],['Soliq hisoboti','Yangilangan: 15.10.2025','Davlat soliq idoralariga topshiriladigan jami deklaratsiyalar va to‘lovlar tahlili',asset.reportTax],['Pul oqimi hisoboti','Yangilangan: Bugun, 09:15','Kompaniyaning barcha operatsion, investitsion va moliyaviy pul oqimlari dinamikasi',asset.reportCash],['Debitor-kreditor hisoboti','Yangilangan: Bugun, 12:00','Hamkorlar bo‘yicha muddati o‘tgan hamda joriy qarzlar va majburiyatlar balansi',asset.reportDebt],['Ombor hisoboti','Yangilangan: 20.10.2025','Mavjud tovar-moddiy zaxiralarning omborda qolgan qismi va harakat balansi',asset.reportStock]];
export function AccountantReportsPage(){const a=useApp();return <AccountantShell><main className="acc-main acc-reports"><AccountantHeader title="Hisob hisobotlari" subtitle="Moliyaviy hisobotlar va tahlillar"/><div className="acc-report-grid">{reportCards.map(r=><Card key={r[0]}><header><img src={r[3]} alt=""/><span><h2>{r[0]}</h2><small>{r[1]}</small></span></header><p>{r[2]}</p><footer><button onClick={()=>a.notice(`${r[0]} ko‘rish uchun ochildi.`)}>Ko‘rish</button><button onClick={()=>a.notice(`${r[0]} yuklab olishga tayyorlandi.`)}>Yuklab olish</button></footer></Card>)}</div></main></AccountantShell>}

const requests=[['TN-2026-041','Navoiy 28','Beton A50 (120 dona)','48,000,000 UZS','48,000,000 UZS','15.09.2026','Sardor M.','Tasdiqlangan'],['TN-2026-043','Navoiy 28','G‘isht (5000 dona)','15,000,000 UZS','-','17.09.2026','Sardor M.','Kutilmoqda'],['TN-2026-045','Toshkent A-12','Qum (150 m³)','12,000,000 UZS','12,000,000 UZS','14.09.2026','Jamshid K.','Tasdiqlangan'],['TN-2026-046','Navoiy 28','Sanitariya-texnika ...','8,600,000 UZS','-','18.09.2026','Sardor M.','Rad etilgan']];
export function AccountantRequestsPage(){const a=useApp();return <AccountantShell><main className="acc-main acc-requests"><AccountantHeader title="Talabnomalarga pul ajratish" subtitle="Ombordan kelgan talabnomalarga moliyaviy mablag‘ ajratish"/><div className="acc-kpis five">{[['JAMI TALABNOMALAR','24 ta'],['KUTILMOQDA','8 ta'],['TASDIQLANGAN','12 ta'],['RAD ETILGAN','4 ta'],['AJRATILGAN MABLAG‘','186,500,000 UZS']].map((x,i)=><article key={x[0]}><span>{x[0]}</span><strong className={i===1?'orange':i===2?'green':i===3?'red':''}>{x[1]}</strong></article>)}</div><div className="acc-row-toolbar"><div><button className="outline">▣ Sana: 01.09 - 30.09.2026</button><select><option>Obyekt: Hammasi</option></select><select><option>Holati: Hammasi</option></select></div><CrudButton action="create" onClick={()=>a.notice('Yangi ajratma formasi demo rejimida.')}>+ Yangi ajratma</CrudButton></div><Card className="acc-table-card acc-request-table"><h2>Talabnomalarga pul ajratish ro‘yxati</h2><Table columns={['TALABNOMA RAQAMI','OBYEKT','MATERIALLAR','SO‘RALGAN SUMMA','AJRATILGAN SUMMA','SANA','MAS’UL','HOLATI']} rows={requests} grid="140px 140px 1.2fr 150px 170px 130px 140px 140px"/></Card></main></AccountantShell>}

function Field({label,children}:{label:string;children:ReactNode}){return <label className="acc-field"><span>{label}</span>{children}</label>}
export function AccountantProfilePage(){const a=useApp();return <AccountantShell><main className="acc-main acc-profile-page"><AccountantHeader title="Profil" subtitle="Shaxsiy ma’lumotlaringizni ko‘rish va tahrirlash"/><form className="acc-profile-card" onSubmit={e=>{e.preventDefault();a.notice('Profil ma’lumotlari saqlandi.')}}><div className="acc-profile-top"><div className="acc-photo-box"><img src={asset.portrait} alt="Profil rasmi"/><div><button type="button"><img src={asset.upload} alt=""/>Rasm yuklash</button><button type="button"><img src={asset.remove} alt=""/>Rasm o‘chirish</button></div></div><div className="acc-profile-fields"><Field label="Ismi"><input defaultValue="Abror"/></Field><Field label="Familiya"><input defaultValue="Abrorov"/></Field><Field label="Tel raqam"><input defaultValue="+99894 364 77 03"/></Field><Field label="Parol"><input defaultValue="1q2w3e4r"/></Field></div></div><div className="acc-profile-bottom"><Field label="Lavozim"><select><option>Prorab</option></select></Field><Field label="Obyektga biriktirish"><select><option>-</option></select></Field><Field label="Biriktirilgan obyectlar"><div className="acc-tags">{['Navoiy ko’cha 28','Darxon avenyu','Yakkasaroy 13/10','Mirobod barpu turarjoy','Yunsobot building'].map(x=><span key={x}>{x} ×</span>)}</div></Field><Field label="Holati"><select><option>faol</option></select></Field><Field label="Lavozimga tainlangan sana"><input placeholder="KK/OO/YYYY"/></Field></div><footer><button type="button" className="outline" onClick={()=>a.setRole('manager')}>Profildan chiqish <img src={asset.logout} alt=""/></button><div><button type="reset" className="outline"><img src={asset.reset} alt=""/>Tozalash</button><button>Tahrirlashni tasdiqlash</button></div></footer></form></main></AccountantShell>}
export function AccountantNotFoundPage(){const a=useApp();return <div className="acc-not-found"><button onClick={()=>a.go(76)} aria-label="Bosh sahifaga qaytish"><span>Xat</span><img src={asset.constructing} alt=""/><b>4</b><strong>o</strong><b>4</b><small>Sahifada nosozlik yuz berdi</small></button></div>}
