import {useState,type CSSProperties,type FormEvent,type ReactNode} from 'react';
import {useApp} from '../ui/App';
import {roles,type Role} from '../ui/roles';

const A='/assets/';
const asset={logo:A+'super-78786.png',profile:A+'super-b66a7.png',bell:A+'super-bebe8.png',chevron:A+'super-cad8e.png',companies:A+'super-81dc8.svg',admins:A+'super-770be.svg',integrations:A+'super-03f22.png',logs:A+'super-f5cb4.svg',settings:A+'super-3c8ad.svg',search:A+'super-35e4d.svg',reset:A+'super-9e5ea.png',back:A+'super-5aaa3.svg',pin:A+'super-771d0.svg',globe:A+'super-e90e9.svg',calendar:A+'super-469ec.svg',portrait:A+'super-8f320.png',upload:A+'super-403bd.png',remove:A+'super-3c902.png',logout:A+'super-a2f9e.png',constructing:A+'super-8170b.png'};

const nav=[
  {screen:41,label:'Kompaniyalar',icon:asset.companies},
  {screen:46,label:'Administratorlar',icon:asset.admins},
  {screen:49,label:'Integratsiyalar',icon:asset.integrations},
  {screen:50,label:'Tizim jurnali',icon:asset.logs},
  {screen:51,label:'Sozlamalar',icon:asset.settings},
];

function activeSection(screen:number){return [42,43,44,45].includes(screen)?41:[47,48].includes(screen)?46:screen;}

function SuperSidebar(){
  const a=useApp();const active=activeSection(a.screen);
  return <aside className="sa-sidebar"><div className="sa-sidebar-top"><a href="#/screen/41" className="sa-logo"><img src={asset.logo} alt="Barpo AI" width="95" height="52"/></a><nav aria-label="Super admin menyusi">{nav.filter(item=>a.canAccess(item.screen)).map(item=><a key={item.screen} href={`#/screen/${item.screen}`} className={active===item.screen?'active':''}><span className="sa-nav-icon"><img src={item.icon} alt=""/></span><span>{item.label}</span>{active===item.screen&&<i/>}</a>)}</nav></div><div className="sa-sidebar-bottom"><label className="sa-role-picker">Rolni sinash · demo<select value={a.role} onChange={e=>a.setRole(e.target.value as Role)}>{Object.entries(roles).map(([key,value])=><option key={key} value={key}>{value.label}</option>)}</select></label><button className="sa-profile" onClick={()=>a.go(52)}><img src={asset.profile} alt="" width="36" height="36"/><span><b>Otabek R.</b><small>Super admin</small></span></button></div></aside>;
}

function SuperHeader({title,subtitle,back}: {title:string;subtitle:string;back?:boolean}){
  const a=useApp();return <header className="sa-header"><div className="sa-heading-row">{back&&<button className="sa-back" onClick={()=>a.go(41)}><img src={asset.back} alt=""/></button>}<div><h1>{title}</h1><p>{subtitle}</p></div></div><div className="sa-header-tools"><button className="sa-bell" aria-label="Bildirishnomalar" onClick={a.toggleNotifications}><img src={asset.bell} alt=""/><span>4</span></button><label className="sa-language"><select aria-label="Til" value={a.language} onChange={e=>a.setLanguage(e.target.value)}><option>UZ</option><option>RU</option></select><img src={asset.chevron} alt=""/></label></div></header>;
}

function SuperShell({children,height=960}:{children:ReactNode;height?:number}){return <div className="sa-shell" style={{'--sa-height':`${height}px`} as CSSProperties}><div className="sa-sidebar-slot"><SuperSidebar/></div>{children}</div>}

const companies=[['Nova Tech','nova.uz','Business','24','Faol','24.02.2025'],['Orzu Education','nova.uz','Enterprise','54','To‘xtatilgan','24.02.2025'],['Baraka Retail','nova.uz','Business','556','Faol','24.02.2025'],['Atlas Group','nova.uz','Start','89','Faol','24.02.2025'],['Zamin Logistics','nova.uz','Business','32','Faol','24.02.2025']];

function CompaniesBody(){const a=useApp();const [query,setQuery]=useState('');const rows=companies.filter(r=>r[0].toLowerCase().includes(query.toLowerCase())||r[1].includes(query.toLowerCase()));return <main className="sa-main sa-companies"><SuperHeader title="Kompaniyalar" subtitle="Kompaniya profillari, holati va ulanishlarini boshqaring"/><section className="sa-card sa-companies-card"><div className="sa-toolbar"><div className="sa-toolbar-left"><label className="sa-search"><img src={asset.search} alt=""/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Kompaniya yoki domen qidirish"/></label><select><option>Barcha holatlar</option><option>Faol</option><option>To‘xtatilgan</option></select><select><option>Barcha tariflar</option><option>Start</option><option>Business</option><option>Enterprise</option></select></div><div className="sa-toolbar-right"><button className="sa-outline" onClick={()=>a.notice('Kompaniyalar ro‘yxati eksport qilinadi.')}>Eksport</button><button className="sa-primary" onClick={()=>a.go(42)}>+ Kompaniya ochish</button></div></div><div className="sa-company-table"><div className="sa-company-head"><span>KOMPANIYA</span><span>DOMEN</span><span>TARIF</span><span>XODIMLAR</span><span>HOLAT</span><span>SANA</span></div>{rows.map(row=><button className="sa-company-row" key={row[0]} onClick={()=>a.go(45)}>{row.map((cell,index)=><span key={index} className={index===4?(cell==='Faol'?'ok':'bad'):''}>{cell}</span>)}</button>)}</div></section></main>}

export function CompaniesPage(){return <SuperShell height={1040}><CompaniesBody/></SuperShell>}

function Modal({children,className=''}:{children:ReactNode;className?:string}){return <div className="sa-modal-shade"><section className={`sa-modal ${className}`}>{children}</section></div>}
function Field({label,children,wide=false}:{label:string;children:ReactNode;wide?:boolean}){return <label className={wide?'sa-field wide':'sa-field'}><span>{label}</span>{children}</label>}

export function CompanyWizardPage({step}:{step:1|2|3}){const a=useApp();const submit=(e:FormEvent)=>{e.preventDefault();if(step<3)a.go(42+step);else{a.notice('Yangi kompaniya demo ro‘yxatiga saqlandi.');a.go(41)}};return <SuperShell height={653}><CompaniesBody/><Modal className={`sa-company-modal step-${step}`}><form onSubmit={submit}>{step===1&&<><header><h2>Kompaniya ma’lumotlari</h2><p>Tashkilotning rasmiy nomi va aloqa ma’lumotlari.</p></header><div className="sa-form-grid"><Field label="Kompaniya nomi"><input defaultValue="Albus Premyer" required/></Field><Field label="Mail manzil"><input defaultValue="company@example.uz" type="email" required/></Field><Field label="Mas’ul shaxs"><input defaultValue="Botirov Sadriddin"/></Field><Field label="Telefon raqami"><input defaultValue="+998983126545"/></Field><Field label="Yuridik manzil" wide><span className="sa-input-icon"><img src={asset.pin} alt=""/><input defaultValue="Kiritng"/></span></Field></div></>}{step===2&&<><header><h2>Yuridik va domen</h2><p>Ro‘yxatdan o‘tgan rekvizitlar va tizim manzili.</p></header><div className="sa-form-grid"><Field label="STIR"><input placeholder="9 xonali STIR" required/></Field><Field label="Tashkiliy shakl"><select defaultValue=""><option value="" disabled>Tanlang</option><option>MChJ</option><option>AJ</option></select></Field><Field label="Kompaniya" wide><span className="sa-input-icon"><img src={asset.globe} alt=""/><input defaultValue="kompaniya.nova.uz"/></span></Field></div></>}{step===3&&<><header><h2>Tarif va holat</h2><p>Kompaniya uchun boshlang‘ich xizmat rejasini tanlang.</p></header><div className="sa-form-grid"><Field label="Tarif" wide><select defaultValue=""><option value="" disabled>Tanlang</option><option>Start</option><option>Business</option><option>Enterprise</option></select></Field><Field label="Holat"><input defaultValue="Faol"/></Field><Field label="Boshlanish sanasi"><span className="sa-input-icon"><img src={asset.calendar} alt=""/><input defaultValue="14.09.2026"/></span></Field></div></>}<footer><div>{step>1&&<button type="button" className="sa-outline" onClick={()=>a.go(41+step)}>Orqaga</button>}<button type="reset" className="sa-outline"><img src={asset.reset} alt=""/>Tozalash</button></div><button className="sa-primary">{step===3?'Saqlash':'Keyingisi'}</button></footer></form></Modal></SuperShell>}

export function CompanyEditPage(){const a=useApp();return <SuperShell height={1040}><main className="sa-main sa-company-edit"><SuperHeader back title="Nova Tech kompaniyasini tahrirlash" subtitle="Kompaniya profili va boshqaruv sozlamalarini yangilang"/><form className="sa-edit-form" onSubmit={e=>{e.preventDefault();a.notice('Kompaniya ma’lumotlari saqlandi.')}}><div className="sa-form-grid"><Field label="Kompaniya nomi"><input defaultValue="Albus Premyer"/></Field><Field label="Mail manzil"><input defaultValue="company@example.uz"/></Field><Field label="Mas’ul shaxs"><input defaultValue="Botirov Sadriddin"/></Field><Field label="Telefon raqami"><input defaultValue="+998983126545"/></Field><Field label="Yuridik manzil" wide><span className="sa-input-icon"><img src={asset.pin} alt=""/><input defaultValue="Kiritng"/></span></Field><Field label="STIR"><input defaultValue="309 845 217"/></Field><Field label="Tashkiliy shakl"><select><option>-</option><option>MChJ</option></select></Field><Field label="Kompaniya"><span className="sa-input-icon"><img src={asset.globe} alt=""/><input defaultValue="kompaniya.nova.uz"/></span></Field><Field label="Tarif"><select defaultValue="Business"><option>Business</option><option>Enterprise</option></select></Field><Field label="Holat"><select defaultValue="Faol"><option>Faol</option><option>To‘xtatilgan</option></select></Field><Field label="Boshlanish sanasi"><span className="sa-input-icon"><img src={asset.calendar} alt=""/><input defaultValue="14.09.2026"/></span></Field></div><footer><div><button type="reset" className="sa-outline"><img src={asset.reset} alt=""/>Tozalash</button><button type="button" className="sa-danger" onClick={()=>a.notice('Demo yozuv o‘chirilmadi.')}>O‘chirish</button></div><button className="sa-primary">Saqlash</button></footer></form></main></SuperShell>}

const administrators=[['Otabek Rahimov','+998943647751','Platforma','Super admin','Hozir','Faol','22.12.2026'],['Nodir Ismoilov','+998943647653','Barpo Development','Kompaniya admini','Bugun, 10:04','Faol','11.06.2025'],['Diyor Hamidov','+998945447703','Grand Build','Kompaniya admini','Kecha, 17:21','Faol','02.10.2026'],['Sarvar Azizov','+998943665703','Orient Group','Kompaniya admini','Kecha, 09:21','Faol','18.05.2025']];

function AdministratorsBody(){const a=useApp();return <main className="sa-main sa-admins"><SuperHeader title="Administratorlar" subtitle="Platforma va kompaniya administratorlari vakolatlarini boshqarish"/><section className="sa-admin-stats">{[['JAMI ADMINISTRATORLAR','36','32 ta faol'],['SUPER ADMIN','4','O‘zgarmagan'],['KOMPANIYA ADMINI','28','↗ +3 bu oy'],['TAKLIF YUBORILGAN','4','Tasdiq kutilmoqda']].map(x=><article key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong><small>{x[2]}</small></article>)}</section><div className="sa-admin-toolbar"><label className="sa-search"><span>⌕</span><input placeholder="Qidirish..."/></label><select><option>Barcha holatlar</option></select><select><option>14.09.2026</option></select><button className="sa-primary" onClick={()=>a.go(47)}>＋ Administrator tayinlash</button></div><section className="sa-card sa-admin-list"><header><h2>Administratorlar ro‘yxati</h2><p>Vakolat, qamrov va oxirgi faollik</p></header><div className="sa-admin-head"><span>ADMINISTRATOR</span><span>RAQAM</span><span>TASHKILOT</span><span>VAKOLAT</span><span>OXIRGI KIRISH</span><span>HOLAT</span><span>SANA</span></div>{administrators.map(row=><button className="sa-admin-row" key={row[0]} onClick={()=>a.go(48)}>{row.map((cell,i)=><span className={i===5?'ok':''} key={i}>{cell}</span>)}</button>)}</section></main>}

export function AdministratorsPage(){return <SuperShell height={689}><AdministratorsBody/></SuperShell>}

export function AdministratorFormPage({edit=false}:{edit?:boolean}){const a=useApp();return <SuperShell height={689}><AdministratorsBody/><Modal className="sa-admin-modal"><form onSubmit={e=>{e.preventDefault();a.notice(edit?'Administrator yangilandi.':'Administratorga taklif yuborildi.');a.go(46)}}><header><div><h2>{edit?'Administratorni tahrirlash':'Administrator ma’lumotlari'}</h2>{!edit&&<p>Taklif foydalanuvchining elektron pochtasiga yuboriladi</p>}</div><button type="button" onClick={()=>a.go(46)}>×</button></header><div className="sa-form-grid"><Field label="Ismi"><input defaultValue="Dilshod"/></Field><Field label="Familiya"><input defaultValue="Karimov"/></Field><Field label="Elektron pochta" wide><input defaultValue="dilshod.karimov@barpo.uz"/><small>Ushbu manzil tizimga kirish uchun ishlatiladi</small></Field><Field label="Telefon raqami" wide><input defaultValue="+998 90 123 45 67"/></Field><Field label="Administrator roli"><select><option>Kompaniya admini</option><option>Super admin</option></select></Field><Field label="Tashkilot"><select><option>Barpo Development</option></select></Field><Field label="Boshqaruv qamrovi" wide><select><option>Barcha obyektlar</option></select></Field></div><footer><div><button type="reset" className="sa-outline"><img src={asset.reset} alt=""/>Tozalash</button>{edit&&<button type="button" className="sa-danger">O‘chirish</button>}</div><button className="sa-primary">{edit?'Saqlash':'Qo‘shishni tasdiqlash'}</button></footer></form></Modal></SuperShell>}

const services=[['Didox','Soliq hujjatlari va elektron hisob-fakturalar','Bugun, 10:42','Ulangan','▣'],['iHamkor','Bank hisoblari va tranzaksiyalar','Bugun, 09:18','Ulangan','▥'],['Telegram bot','Xodimlar uchun tezkor bildirishnomalar','Kecha, 18:05','Ulangan','➤'],['SMS xizmati','Tasdiqlash kodlari va ogohlantirishlar','Sinxronlanmagan','Uzilgan','◯']];
export function IntegrationsPage(){const a=useApp();return <SuperShell height={960}><main className="sa-main sa-integrations"><SuperHeader title="Integratsiyalar" subtitle="Tashqi tizimlar ulanishi va ma’lumot almashinuvini boshqaring"/><section className="sa-integration-stats">{[['4','Xizmatlar'],['3','Faol ulanish'],['1','E’tibor talab qiladi']].map(x=><article key={x[1]}><strong>{x[0]}</strong><span>{x[1]}</span></article>)}</section><section className="sa-card sa-services"><header><h2>Ulangan xizmatlar</h2><p>ERP bilan ishlaydigan tashqi xizmatlar holati</p></header><div className="sa-service-grid">{services.map(s=><article key={s[0]}><div className="sa-service-title"><i>{s[4]}</i><span><b>{s[0]}</b><small>{s[1]}</small></span><em className={s[3]==='Uzilgan'?'bad':''}>● {s[3]}</em></div><div className="sa-service-footer"><span><small>Oxirgi sinxronizatsiya</small><b>{s[2]}</b></span><button className="sa-primary" onClick={()=>a.notice(`${s[0]} sozlamalari demo rejimida.`)}>Sozlash</button></div></article>)}</div></section></main></SuperShell>}

const logs=[['13.09.2026 10:42','Otabek Rahimov','Kirish','Dashboard','192.168.1.24','Muvaffaqiyatli'],['13.09.2026 10:31','Dilshod Karimov','O‘zgartirish','Smetalar','192.168.1.42','Muvaffaqiyatli'],['13.09.2026 10:18','Madina Aliyeva','O‘chirish','Xomashyolar','10.10.0.18','Rad etildi'],['13.09.2026 09:54','Otabek Rahimov','O‘zgartirish','Ruxsatlar','192.168.1.24','Muvaffaqiyatli'],['13.09.2026 09:20','Sarvar Tursunov','Kirish','Mobil ilova','172.16.0.36','Muvaffaqiyatli'],['12.09.2026 18:45','Nilufar Sobirova','O‘zgartirish','Foydalanuvchilar','192.168.1.53','Muvaffaqiyatli'],['12.09.2026 17:12','Anonim','Kirish','Autentifikatsiya','85.117.22.14','Rad etildi']];
export function LogsPage(){return <SuperShell height={817}><main className="sa-main sa-logs"><SuperHeader title="Tizim jurnali" subtitle="Platformadagi xavfsizlik va foydalanuvchi hodisalarini kuzating"/><div className="sa-log-filters"><select><option>Sana: 13.09.2026</option></select><select><option>Foydalanuvchi: Barchasi</option></select><select><option>Amal turi: Barchasi</option></select></div><section className="sa-card sa-log-card"><header><h2>So‘nggi hodisalar</h2><p>Jami 2 486 ta yozuv</p></header><div className="sa-log-head"><span>VAQT</span><span>FOYDALANUVCHI</span><span>AMAL TURI</span><span>MODUL</span><span>IP MANZIL</span><span>NATIJA</span></div>{logs.map((row,n)=><div className="sa-log-row" key={n}>{row.map((cell,i)=><span className={i===5?(cell==='Rad etildi'?'bad':'ok'):''} key={i}>{cell}</span>)}</div>)}</section></main></SuperShell>}

export function SuperSettingsPage(){const a=useApp();const [switches,setSwitches]=useState([true,false,true,true]);return <SuperShell height={1024}><main className="sa-main sa-settings"><SuperHeader title="Tizim Sozlamalari" subtitle="Platforma xarakteristikalari va bildirishnomalarni boshqarish"/><section className="sa-card sa-settings-card"><header><h2>Umumiy Sozlamalar</h2><p>Tashkilotingiz uchun standart til, valyuta va vaqt sozlamalarini boshqaring</p></header><div className="sa-settings-fields"><Field label="Platforma nomi" wide><input defaultValue="BuildFlow"/></Field><Field label="Tizim tili (Language)" wide><select><option>O‘zbekcha</option><option>Русский</option></select></Field><Field label="Vaqt mintaqasi" wide><select><option>(UTC+5) Toshkent mintaqasi</option></select></Field><Field label="Tizim valyutasi"><input defaultValue="UZS (so‘m)"/></Field><Field label="Sana formati"><select><option>KK.OO.YYYY</option></select></Field></div><div className="sa-notification-settings"><header><h2>Bildirishnoma sozlamalari</h2><p>Tizim yangiliklari va vazifa eslatmalari yuboriladigan kanallarni tanlang</p></header>{['Email bildirishnomalari','SMS bildirishnomalari','Telegram bildirishnomalari','Vazifa eslatmalari'].map((label,i)=><button key={label} onClick={()=>setSwitches(s=>s.map((v,n)=>n===i?!v:v))}><span><b>{label}</b><small>{['Smeta tasdiqlari va moliyaviy hisobotlar email pochtaga yuboriladi','Favqulodda vazifa o‘zgarishlari va ogohlantirishlar telefon raqamga yuboriladi','BuildFlow boti orqali kunlik vazifa eslatmalarini faollashtirish','Belgilangan muddatdan 24 soat oldin tizimda eslatma ko‘rsatish'][i]}</small></span><i className={switches[i]?'on':''}><u/></i></button>)}</div><footer><button className="sa-primary" onClick={()=>a.notice('Tizim sozlamalari saqlandi.')}>Saqlash</button></footer></section></main></SuperShell>}

export function SuperProfilePage(){const a=useApp();return <SuperShell height={1024}><main className="sa-main sa-profile-page"><SuperHeader title="Profil" subtitle="Shaxsiy ma’lumotlaringizni ko‘rish va tahrirlash"/><form className="sa-card sa-profile-card" onSubmit={e=>{e.preventDefault();a.notice('Profil ma’lumotlari saqlandi.')}}><div className="sa-profile-top"><div className="sa-photo-box"><img className="sa-portrait" src={asset.portrait} alt="Profil rasmi"/><div><button type="button" className="sa-primary"><img src={asset.upload} alt=""/>Rasm yuklash</button><button type="button" className="sa-primary"><img src={asset.remove} alt=""/>Rasm o‘chirish</button></div></div><div className="sa-profile-fields"><Field label="Ismi"><input defaultValue="Abror"/></Field><Field label="Familiya"><input defaultValue="Abrorov"/></Field><Field label="Tel raqam"><input defaultValue="+99894 364 77 03"/></Field><Field label="Parol"><input defaultValue="1q2w3e4r"/></Field></div></div><div className="sa-profile-bottom"><Field label="Lavozim" wide><select><option>Prorab</option></select></Field><Field label="Obyektga biriktirish" wide><select><option>-</option></select></Field><Field label="Biriktirilgan obyectlar" wide><div className="sa-tags">{['Navoiy ko’cha 28','Darxon avenyu','Yakkasaroy 13/10','Mirobod barpu turarjoy','Yunsobot building'].map(x=><span key={x}>{x} ×</span>)}</div></Field><Field label="Holati" wide><select><option>faol</option></select></Field><Field label="Lavozimga tainlangan sana" wide><input placeholder="KK/OO/YYYY"/></Field></div><footer><button type="button" className="sa-outline" onClick={()=>a.setRole('manager')}>Profildan chiqish <img src={asset.logout} alt=""/></button><div><button type="reset" className="sa-outline"><img src={asset.reset} alt=""/>Tozalash</button><button className="sa-primary">Tahrirlashni tasdiqlash</button></div></footer></form></main></SuperShell>}

export function SuperNotFoundPage(){return <div className="sa-404"><div><span className="sa-xato">Xato</span><span className="sa-four one">4</span><span className="sa-four two">4</span><img src={asset.constructing} alt=""/><p>Sahifada nosozlik yuz berdi</p></div></div>}
