import {
  Activity,
  AlertTriangle,
  BadgeDollarSign,
  BarChart3,
  Boxes,
  Building2,
  Calculator,
  CalendarDays,
  Cctv,
  Circle,
  ClipboardList,
  CreditCard,
  FileInput,
  FileText,
  GitCompare,
  HandCoins,
  Landmark,
  LayoutDashboard,
  LifeBuoy,
  ListChecks,
  Lock,
  Package,
  PiggyBank,
  Plug,
  Receipt,
  Scale,
  ScrollText,
  Settings,
  ShieldCheck,
  TrendingUp,
  UserCog,
  Users,
  Wallet,
  type LucideProps,
} from 'lucide-react';
import type { ComponentType } from 'react';

/** Navigatsiyada ishlatiladigan ikonkalar; butun lucide to'plamini bundlega tortmaslik uchun aniq ro'yxat. */
export const navIcons: Record<string, ComponentType<LucideProps>> = {
  Activity,
  AlertTriangle,
  BadgeDollarSign,
  BarChart3,
  Boxes,
  Building2,
  Calculator,
  CalendarDays,
  Cctv,
  ClipboardList,
  CreditCard,
  FileInput,
  FileText,
  GitCompare,
  HandCoins,
  Landmark,
  LayoutDashboard,
  LifeBuoy,
  ListChecks,
  Lock,
  Package,
  PiggyBank,
  Plug,
  Receipt,
  Scale,
  ScrollText,
  Settings,
  ShieldCheck,
  TrendingUp,
  UserCog,
  Users,
  Wallet,
};
export function NavIcon({ name, size = 18 }: { name: string; size?: number }) {
  const Cmp = navIcons[name] ?? Circle;
  return <Cmp size={size} />;
}
